package main

// Generated by gloat (engine LG). The program's bytecode bundle is
// embedded and executed on the let-go VM; the blank-imported lowered
// packages register native Go overrides that replace eligible fns as
// each namespace loads. When -main lowered, entry is a direct native
// call; otherwise the driver main chunk runs it on the VM.

import (
	"bytes"
	_ "embed"
	"fmt"
	"os"

	"github.com/nooga/let-go/pkg/bytecode"
	"github.com/nooga/let-go/pkg/compiler"
	"github.com/nooga/let-go/pkg/resolver"
	"github.com/nooga/let-go/pkg/rt"
	"github.com/nooga/let-go/pkg/vm"
LOWERED-IMPORTS
)

//go:embed program.lgb
var lgbData []byte

func fail(err error) {
	fmt.Fprint(os.Stderr, vm.FormatError(err))
	os.Exit(1)
}

func main() {
	// Importing pkg/compiler booted core from its embedded bundle; the
	// resolver (nil paths) lets replayed requires load embedded nses.
	ctx := compiler.NewCompiler(vm.NewConsts(), rt.NS("user"))
	rt.SetNSLoader(resolver.NewNSResolver(ctx, nil))
	defer rt.ShutdownAllPods()

	args := os.Args[1:]
	argv := make([]vm.Value, len(args))
	var cla vm.Value = vm.NIL
	if len(args) > 0 {
		for i, a := range args {
			argv[i] = vm.String(a)
		}
		cla = vm.NewList(argv)
	}
	rt.CoreNS.Lookup("*command-line-args*").(*vm.Var).SetRoot(cla)

	resolve := func(nsName, name string) *vm.Var {
		n := rt.DefNSBare(nsName)
		if v := n.LookupLocal(vm.Symbol(name)); v != nil {
			return v
		}
		return n.DefStub(name)
	}
	unit, err := bytecode.DecodeToExecUnit(bytes.NewReader(lgbData), resolve)
	if err != nil {
		fail(err)
	}
	for _, name := range unit.NSOrder {
		chunk := unit.NSChunks[name]
		if chunk == nil || chunk == unit.MainChunk {
			continue
		}
		f := vm.NewFrame(chunk, nil)
		_, err := f.RunProtected()
		vm.ReleaseFrame(f)
		if err != nil {
			fail(fmt.Errorf("loading namespace %s: %w", name, err))
		}
		// Drain this ns's Go-native overrides (no-op when none).
		rt.ApplyGoOverrides(rt.LookupNS(name))
	}
	_ = argv
ENTRY-CODE
}
