package main

// Generated by gloat (engine LG). The program's bytecode bundle is
// embedded and executed on the let-go VM; the blank-imported lowered
// packages register native Go overrides that replace eligible fns as
// each namespace loads. When -main lowered, entry is a direct native
// call; otherwise the driver main chunk runs it on the VM.

import (
	_ "embed"
	"fmt"
	"os"

	"github.com/nooga/let-go/pkg/rt"
	"github.com/nooga/let-go/pkg/vm"
LOWERED-IMPORTS
)

//go:embed program.lgb
var lgbData []byte

func fail(err error) {
	fmt.Fprint(os.Stderr, vm.FormatError(err))
	os.Exit(1)
}

func main() {
	// Runtime-only boot: core loads from its embedded bundle, so neither
	// the compiler nor the resolver is linked into the binary. Replayed
	// requires resolve against namespaces the loop below has already
	// installed, which is every namespace the bundle carries.
	ec, err := rt.BootCore()
	if err != nil {
		fail(err)
	}
	defer rt.ShutdownAllPods()

	args := os.Args[1:]
	argv := make([]vm.Value, len(args))
	for i, a := range args {
		argv[i] = vm.String(a)
	}
	rt.SetCommandLineArgs(args)

	unit, err := rt.DecodeExecUnit(lgbData)
	if err != nil {
		fail(err)
	}
	// MainChunk is skipped here on purpose: gloat's driver chunk calls
	// -main, so replaying it would run the program before (and in the
	// :direct case in addition to) the entry call below. rt.RunExecUnit
	// skips it too but drains no overrides, and rt.LoadProgramNamespaces
	// drains them but replays MainChunk — neither fits this shape.
	for _, name := range unit.NSOrder {
		chunk := unit.NSChunks[name]
		if chunk == nil || chunk == unit.MainChunk {
			continue
		}
		f := vm.NewFrame(chunk, nil)
		_, err := f.RunProtected()
		vm.ReleaseFrame(f)
		if err != nil {
			fail(fmt.Errorf("loading namespace %s: %w", name, err))
		}
		// Drain this ns's Go-native overrides (no-op when none).
		rt.ApplyGoOverrides(rt.LookupNS(name))
	}
	_ = ec
	_ = argv
ENTRY-CODE
}
