#!/usr/bin/env bash

# Tests for gloat CLI

source "$(dirname "${BASH_SOURCE[0]}")/init"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
GLOAT_BIN=$SCRIPT_DIR/../bin/gloat
FIXTURES_DIR=$SCRIPT_DIR/fixtures

# Test help/version (exit 129 is normal for git-based help display)
try "$GLOAT_BIN"
is "$rc" 129 "'gloat' with no args exits 129"
has "$got" "usage:" "'gloat' with no args shows usage"

try "$GLOAT_BIN -h"
is "$rc" 129 "'gloat -h' exits 129"
has "$got" "usage:" "'gloat -h' shows usage"

try "$GLOAT_BIN --version"
is "$rc" 0 "'gloat --version' exits 0"
has "$got" "gloat v" "'gloat --version' shows gloat version"
has "$got" "glj   v" "'gloat --version' shows glj version"

try "$GLOAT_BIN --which=glj"
is "$rc" 0 "'gloat --which=glj' exits 0"
has "$got" "/glj" "'gloat --which=glj' prints glj path"

try "$GLOAT_BIN --which=glj,go"
is "$rc" 0 "'gloat --which=glj,go' exits 0"
has "$got" "/glj" "'gloat --which=glj,go' prints glj path"
has "$got" "/go" "'gloat --which=glj,go' prints go path"

try "$GLOAT_BIN --which=wasmtime"
is "$rc" 0 "'gloat --which=wasmtime' exits 0"
has "$got" "/wasmtime" "'gloat --which=wasmtime' prints managed wasmtime path"

try "$GLOAT_BIN --which=definitely-not-a-gloat-command"
is "$rc" 1 "'gloat --which=missing' exits 1"
is "$got" "" "'gloat --which=missing' is quiet"

try "$GLOAT_BIN --which=ls,wasmtime,definitely-not-a-gloat-command,bash"
is "$rc" 1 "'gloat --which' exits 1 if any command is missing"
has "$got" "/ls" "'gloat --which' prints paths before missing command"
has "$got" "/wasmtime" "'gloat --which' prints managed paths"
has "$got" "/bash" "'gloat --which' continues after missing command"

try "$GLOAT_BIN --which="
is "$rc" 1 "'gloat --which=' exits 1"
has "$got" "requires a command name" "'gloat --which=' reports empty command"

try "$GLOAT_BIN --which=glj,"
is "$rc" 1 "'gloat --which=glj,' exits 1"
has "$got" "empty command name" "'gloat --which=glj,' reports empty command"

try "$GLOAT_BIN --glj"
is "$rc" 129 "'gloat --glj' is no longer accepted"

try "$GLOAT_BIN --shell -- 'printf \"%s\\n\" \"\${PATH%%:*}\"' 2>/dev/null"
is "$rc" 0 "'gloat --shell' exits 0"
ok "$([[ $got == "$PROJECT_ROOT/.cache/"* ]])" \
  "'gloat --shell' promotes gloat cache paths"

# Test stdout modes
cd "$FIXTURES_DIR" || bail-out "Cannot cd to fixtures"

try "$GLOAT_BIN hello.ys -t clj"
is "$rc" 0 "'gloat hello.ys -t clj' exits 0"
has "$got" "(ns " "'gloat hello.ys -t clj' outputs Clojure"

if [[ ${RUN_SLOW_TESTS:-} ]]; then
  # Test Go stdout mode
  try "$GLOAT_BIN hello.ys -t go"
  is "$rc" 0 "'gloat hello.ys -t go' exits 0"
  has "$got" "// Code generated by glojure" "'gloat hello.ys -t go' outputs Go code"
fi

# Test error handling
try "$GLOAT_BIN nonexistent.ys"
is "$rc" 1 "'gloat nonexistent.ys' exits 1"
has "$got" "does not exist" "'gloat nonexistent.ys' shows error"

# Test -t .ext shorthand
rm -f "$FIXTURES_DIR/hello.glj"
try "$GLOAT_BIN hello.ys -t .glj"
is "$rc" 0 "'gloat hello.ys -t .glj' exits 0"
ok "$([[ -f $FIXTURES_DIR/hello.glj ]])" "'gloat hello.ys -t .glj' creates hello.glj"
rm -f "$FIXTURES_DIR/hello.glj"

if [[ ${RUN_SLOW_TESTS:-} ]]; then
  # Test -t .go shorthand
  rm -f "$FIXTURES_DIR/hello.go"
  try "$GLOAT_BIN hello.ys -t .go"
  is "$rc" 0 "'gloat hello.ys -t .go' exits 0"
  ok "$([[ -f $FIXTURES_DIR/hello.go ]])" "'gloat hello.ys -t .go' creates hello.go"
  rm -f "$FIXTURES_DIR/hello.go"
fi

# Test fail-fast when output exists (file)
touch "$FIXTURES_DIR/exists-file"
try "$GLOAT_BIN hello.ys -o $FIXTURES_DIR/exists-file"
is "$rc" 1 "'gloat' fails when output file exists"
has "$got" "Output already exists" "'gloat' shows error for existing file"
rm -f "$FIXTURES_DIR/exists-file"

# Test fail-fast when output exists (directory where file expected)
mkdir -p "$FIXTURES_DIR/exists-dir"
try "$GLOAT_BIN hello.ys -o $FIXTURES_DIR/exists-dir"
is "$rc" 1 "'gloat' fails when output dir exists where file expected"
has "$got" "Output already exists" "'gloat' shows error for existing dir"
rmdir "$FIXTURES_DIR/exists-dir"

# Test fail-fast when file exists where directory expected
touch "$FIXTURES_DIR/exists-as-file"
try "$GLOAT_BIN hello.ys -o $FIXTURES_DIR/exists-as-file/"
is "$rc" 1 "'gloat' fails when file exists where dir expected"
has "$got" "Output already exists" "'gloat' shows error for file blocking dir"
rm -f "$FIXTURES_DIR/exists-as-file"

# Test multiple input files rejection
try "$GLOAT_BIN hello.ys hello.ys"
is "$rc" 1 "'gloat f1 f2' exits 1"
has "$got" "Multiple input files require -o output" \
  "'gloat f1 f2' shows multiple files error"

done-testing
