#!/usr/bin/env bash

# Tests for gloat CLI

source "$(dirname "${BASH_SOURCE[0]}")/init"

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
GLOAT_BIN=$SCRIPT_DIR/../bin/gloat
FIXTURES_DIR=$SCRIPT_DIR/fixtures

# Test help/version (exit 129 is normal for git-based help display)
try "$GLOAT_BIN"
is "$rc" 129 "'gloat' with no args exits 129"
has "$got" "usage:" "'gloat' with no args shows usage"

try "$GLOAT_BIN -h"
is "$rc" 129 "'gloat -h' exits 129"
has "$got" "usage:" "'gloat -h' shows usage"

try "$GLOAT_BIN --version"
is "$rc" 0 "'gloat --version' exits 0"
has "$got" "version" "'gloat --version' shows version"

# Test stdout modes
cd "$FIXTURES_DIR" || bail-out "Cannot cd to fixtures"

try "$GLOAT_BIN hello.ys -t clj"
is "$rc" 0 "'gloat hello.ys -t clj' exits 0"
has "$got" "(ns " "'gloat hello.ys -t clj' outputs Clojure"

if [[ ${RUN_SLOW_TESTS:-} ]]; then
  # Test Go stdout mode
  try "$GLOAT_BIN hello.ys -t go"
  is "$rc" 0 "'gloat hello.ys -t go' exits 0"
  has "$got" "// Code generated by glojure" "'gloat hello.ys -t go' outputs Go code"
fi

# Test error handling
try "$GLOAT_BIN nonexistent.ys"
is "$rc" 1 "'gloat nonexistent.ys' exits 1"
has "$got" "does not exist" "'gloat nonexistent.ys' shows error"

# Test -t .ext shorthand
rm -f "$FIXTURES_DIR/hello.glj"
try "$GLOAT_BIN hello.ys -t .glj"
is "$rc" 0 "'gloat hello.ys -t .glj' exits 0"
ok "$([[ -f $FIXTURES_DIR/hello.glj ]])" "'gloat hello.ys -t .glj' creates hello.glj"
rm -f "$FIXTURES_DIR/hello.glj"

if [[ ${RUN_SLOW_TESTS:-} ]]; then
  # Test -t .go shorthand
  rm -f "$FIXTURES_DIR/hello.go"
  try "$GLOAT_BIN hello.ys -t .go"
  is "$rc" 0 "'gloat hello.ys -t .go' exits 0"
  ok "$([[ -f $FIXTURES_DIR/hello.go ]])" "'gloat hello.ys -t .go' creates hello.go"
  rm -f "$FIXTURES_DIR/hello.go"
fi

# Test fail-fast when output exists (file)
touch "$FIXTURES_DIR/exists-file"
try "$GLOAT_BIN hello.ys -o $FIXTURES_DIR/exists-file"
is "$rc" 1 "'gloat' fails when output file exists"
has "$got" "Output already exists" "'gloat' shows error for existing file"
rm -f "$FIXTURES_DIR/exists-file"

# Test fail-fast when output exists (directory where file expected)
mkdir -p "$FIXTURES_DIR/exists-dir"
try "$GLOAT_BIN hello.ys -o $FIXTURES_DIR/exists-dir"
is "$rc" 1 "'gloat' fails when output dir exists where file expected"
has "$got" "Output already exists" "'gloat' shows error for existing dir"
rmdir "$FIXTURES_DIR/exists-dir"

# Test fail-fast when file exists where directory expected
touch "$FIXTURES_DIR/exists-as-file"
try "$GLOAT_BIN hello.ys -o $FIXTURES_DIR/exists-as-file/"
is "$rc" 1 "'gloat' fails when file exists where dir expected"
has "$got" "Output already exists" "'gloat' shows error for file blocking dir"
rm -f "$FIXTURES_DIR/exists-as-file"

# Test multiple input files rejection
try "$GLOAT_BIN hello.ys hello.ys"
is "$rc" 1 "'gloat f1 f2' exits 1"
has "$got" "Multiple input files not supported" \
  "'gloat f1 f2' shows multiple files error"
has "$got" "Did you mean" \
  "'gloat f1 f2' suggests -o flag"

done-testing
