// Code generated by glojure codegen. DO NOT EDIT.

package fs

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	pkgmap6 "github.com/glojurelang/glojure/pkg/pkgmap"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	os5 "os"
	exec8 "os/exec"
	filepath4 "path/filepath"
	reflect "reflect"
	sync "sync"
	time7 "time"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc1
var aotDirectFn3 lang.FnFunc2
var aotDirectFn4 lang.FnFunc2
var aotDirectFn5 lang.FnFunc1
var aotDirectFn6 lang.FnFunc0
var aotDirectFn7 lang.ArityFn
var aotDirectFn8 lang.FnFunc1
var aotDirectFn9 lang.FnFunc1
var aotDirectFn10 lang.ArityFn
var aotDirectFn11 lang.FnFunc1
var aotDirectFn12 lang.FnFunc1
var aotDirectFn13 lang.FnFunc1
var aotDirectFn14 lang.ArityFn
var aotDirectFn15 lang.FnFunc1
var aotDirectFn16 lang.FnFunc1
var aotDirectFn17 lang.ArityFn
var aotDirectFn18 lang.FnFunc1
var aotDirectFn19 lang.FnFunc1
var aotDirectFn20 lang.FnFunc1
var aotDirectFn21 lang.ArityFn
var aotDirectFn22 lang.FnFunc1
var aotDirectFn23 lang.FnFunc1
var aotDirectFn24 lang.FnFunc1
var aotDirectFn25 lang.FnFunc1
var aotDirectFn26 lang.ArityFn
var aotDirectFn26Arity0 lang.FnFunc0
var aotDirectFn26Arity1 lang.FnFunc1
var aotDirectFn26Arity2 lang.FnFunc2
var aotDirectFn27 lang.ArityFn
var aotDirectFn27Arity0 lang.FnFunc0
var aotDirectFn27Arity1 lang.FnFunc1
var aotDirectFn27Arity2 lang.FnFunc2
var aotDirectFn28 lang.FnFunc1
var aotDirectFn29 lang.FnFunc1
var aotDirectFn30 lang.FnFunc2
var aotDirectFn31 lang.FnFunc1
var aotDirectFn32 lang.ArityFn
var aotDirectFn33 lang.FnFunc1
var aotDirectFn34 lang.FnFunc1
var aotDirectFn35 lang.FnFunc1
var aotDirectFn36 lang.FnFunc1
var aotDirectFn37 lang.FnFunc1
var aotDirectFn38 lang.FnFunc1
var aotDirectFn39 lang.FnFunc1
var aotDirectFn40 lang.FnFunc1
var aotDirectFn41 lang.FnFunc1
var aotDirectFn42 lang.ArityFn
var aotDirectFn43 lang.FnFunc1
var aotDirectFn44 lang.FnFunc1
var aotDirectFn45 lang.ArityFn
var aotDirectFn46 lang.FnFunc1
var aotDirectFn47 lang.FnFunc1
var aotDirectFn48 lang.FnFunc2
var aotDirectFn49 lang.FnFunc1
var aotDirectFn50 lang.ArityFn
var aotDirectFn51 lang.ArityFn

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("ys/fs", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "ys.fs"
func LoadNS() {
	sym__AMP_ := lang.NewSymbolUnchecked("&")
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym_abs := lang.NewSymbolUnchecked("abs")
	sym_abs_QMARK_ := lang.NewSymbolUnchecked("abs?")
	sym_atom := lang.NewSymbolUnchecked("atom")
	sym_basename := lang.NewSymbolUnchecked("basename")
	sym_blank_QMARK_ := lang.NewSymbolUnchecked("blank?")
	sym_chunk_DASH_first := lang.NewSymbolUnchecked("chunk-first")
	sym_chunk_DASH_rest := lang.NewSymbolUnchecked("chunk-rest")
	sym_chunked_DASH_seq_QMARK_ := lang.NewSymbolUnchecked("chunked-seq?")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_conj := lang.NewSymbolUnchecked("conj")
	sym_content := lang.NewSymbolUnchecked("content")
	sym_cp := lang.NewSymbolUnchecked("cp")
	sym_cp_DASH_r := lang.NewSymbolUnchecked("cp-r")
	sym_ctime := lang.NewSymbolUnchecked("ctime")
	sym_cwd := lang.NewSymbolUnchecked("cwd")
	sym_d := lang.NewSymbolUnchecked("d")
	sym_deref := lang.NewSymbolUnchecked("deref")
	sym_dir := lang.NewSymbolUnchecked("dir")
	sym_dir_QMARK_ := lang.NewSymbolUnchecked("dir?")
	sym_dirname := lang.NewSymbolUnchecked("dirname")
	sym_dst := lang.NewSymbolUnchecked("dst")
	sym_e := lang.NewSymbolUnchecked("e")
	sym_empty_QMARK_ := lang.NewSymbolUnchecked("empty?")
	sym_exec_QMARK_ := lang.NewSymbolUnchecked("exec?")
	sym_exists_QMARK_ := lang.NewSymbolUnchecked("exists?")
	sym_f := lang.NewSymbolUnchecked("f")
	sym_file_QMARK_ := lang.NewSymbolUnchecked("file?")
	sym_filename := lang.NewSymbolUnchecked("filename")
	sym_find := lang.NewSymbolUnchecked("find")
	sym_get_DASH_file_DASH_info := lang.NewSymbolUnchecked("get-file-info")
	sym_get_DASH_link_DASH_info := lang.NewSymbolUnchecked("get-link-info")
	sym_glob := lang.NewSymbolUnchecked("glob")
	sym_includes_QMARK_ := lang.NewSymbolUnchecked("includes?")
	sym_l := lang.NewSymbolUnchecked("l")
	sym_link_QMARK_ := lang.NewSymbolUnchecked("link?")
	sym_ls := lang.NewSymbolUnchecked("ls")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_mkdir := lang.NewSymbolUnchecked("mkdir")
	sym_mkdir_DASH_p := lang.NewSymbolUnchecked("mkdir-p")
	sym_mktemp := lang.NewSymbolUnchecked("mktemp")
	sym_mktemp_DASH_d := lang.NewSymbolUnchecked("mktemp-d")
	sym_mtime := lang.NewSymbolUnchecked("mtime")
	sym_multi := lang.NewSymbolUnchecked("multi")
	sym_mv := lang.NewSymbolUnchecked("mv")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_not := lang.NewSymbolUnchecked("not")
	sym_p := lang.NewSymbolUnchecked("p")
	sym_path := lang.NewSymbolUnchecked("path")
	sym_pattern := lang.NewSymbolUnchecked("pattern")
	sym_patterns := lang.NewSymbolUnchecked("patterns")
	sym_prefix := lang.NewSymbolUnchecked("prefix")
	sym_r := lang.NewSymbolUnchecked("r")
	sym_read := lang.NewSymbolUnchecked("read")
	sym_read_QMARK_ := lang.NewSymbolUnchecked("read?")
	sym_readlink := lang.NewSymbolUnchecked("readlink")
	sym_rel := lang.NewSymbolUnchecked("rel")
	sym_rel_QMARK_ := lang.NewSymbolUnchecked("rel?")
	sym_rm := lang.NewSymbolUnchecked("rm")
	sym_rm_DASH_f := lang.NewSymbolUnchecked("rm-f")
	sym_rm_DASH_r := lang.NewSymbolUnchecked("rm-r")
	sym_rmdir := lang.NewSymbolUnchecked("rmdir")
	sym_s := lang.NewSymbolUnchecked("s")
	sym_size_QMARK_ := lang.NewSymbolUnchecked("size?")
	sym_src := lang.NewSymbolUnchecked("src")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_subs := lang.NewSymbolUnchecked("subs")
	sym_swap_BANG_ := lang.NewSymbolUnchecked("swap!")
	sym_touch := lang.NewSymbolUnchecked("touch")
	sym_w := lang.NewSymbolUnchecked("w")
	sym_when_DASH_str := lang.NewSymbolUnchecked("when-str")
	sym_which := lang.NewSymbolUnchecked("which")
	sym_write := lang.NewSymbolUnchecked("write")
	sym_write_QMARK_ := lang.NewSymbolUnchecked("write?")
	sym_x := lang.NewSymbolUnchecked("x")
	sym_ys_DOT_fs := lang.NewSymbolUnchecked("ys.fs")
	sym_z := lang.NewSymbolUnchecked("z")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/atom
	var_clojure_DOT_core_atom := lang.InternVarName(sym_clojure_DOT_core, sym_atom)
	// var clojure.core/chunk-first
	var_clojure_DOT_core_chunk_DASH_first := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_first)
	// var clojure.core/chunk-rest
	var_clojure_DOT_core_chunk_DASH_rest := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_rest)
	// var clojure.core/chunked-seq?
	var_clojure_DOT_core_chunked_DASH_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_chunked_DASH_seq_QMARK_)
	// var clojure.core/conj
	var_clojure_DOT_core_conj := lang.InternVarName(sym_clojure_DOT_core, sym_conj)
	// var clojure.core/deref
	var_clojure_DOT_core_deref := lang.InternVarName(sym_clojure_DOT_core, sym_deref)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/not
	var_clojure_DOT_core_not := lang.InternVarName(sym_clojure_DOT_core, sym_not)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/subs
	var_clojure_DOT_core_subs := lang.InternVarName(sym_clojure_DOT_core, sym_subs)
	// var clojure.core/swap!
	var_clojure_DOT_core_swap_BANG_ := lang.InternVarName(sym_clojure_DOT_core, sym_swap_BANG_)
	// var clojure.string/blank?
	var_clojure_DOT_string_blank_QMARK_ := lang.InternVarName(sym_clojure_DOT_string, sym_blank_QMARK_)
	// var clojure.string/includes?
	var_clojure_DOT_string_includes_QMARK_ := lang.InternVarName(sym_clojure_DOT_string, sym_includes_QMARK_)
	// var ys.fs/abs
	var_ys_DOT_fs_abs := lang.InternVarName(sym_ys_DOT_fs, sym_abs)
	// var ys.fs/abs?
	var_ys_DOT_fs_abs_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_abs_QMARK_)
	// var ys.fs/basename
	var_ys_DOT_fs_basename := lang.InternVarName(sym_ys_DOT_fs, sym_basename)
	// var ys.fs/cp
	var_ys_DOT_fs_cp := lang.InternVarName(sym_ys_DOT_fs, sym_cp)
	// var ys.fs/cp-r
	var_ys_DOT_fs_cp_DASH_r := lang.InternVarName(sym_ys_DOT_fs, sym_cp_DASH_r)
	// var ys.fs/ctime
	var_ys_DOT_fs_ctime := lang.InternVarName(sym_ys_DOT_fs, sym_ctime)
	// var ys.fs/cwd
	var_ys_DOT_fs_cwd := lang.InternVarName(sym_ys_DOT_fs, sym_cwd)
	// var ys.fs/d
	var_ys_DOT_fs_d := lang.InternVarName(sym_ys_DOT_fs, sym_d)
	// var ys.fs/dir?
	var_ys_DOT_fs_dir_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_dir_QMARK_)
	// var ys.fs/dirname
	var_ys_DOT_fs_dirname := lang.InternVarName(sym_ys_DOT_fs, sym_dirname)
	// var ys.fs/e
	var_ys_DOT_fs_e := lang.InternVarName(sym_ys_DOT_fs, sym_e)
	// var ys.fs/empty?
	var_ys_DOT_fs_empty_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_empty_QMARK_)
	// var ys.fs/exec?
	var_ys_DOT_fs_exec_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_exec_QMARK_)
	// var ys.fs/exists?
	var_ys_DOT_fs_exists_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_exists_QMARK_)
	// var ys.fs/f
	var_ys_DOT_fs_f := lang.InternVarName(sym_ys_DOT_fs, sym_f)
	// var ys.fs/file?
	var_ys_DOT_fs_file_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_file_QMARK_)
	// var ys.fs/filename
	var_ys_DOT_fs_filename := lang.InternVarName(sym_ys_DOT_fs, sym_filename)
	// var ys.fs/find
	var_ys_DOT_fs_find := lang.InternVarName(sym_ys_DOT_fs, sym_find)
	// var ys.fs/get-file-info
	var_ys_DOT_fs_get_DASH_file_DASH_info := lang.InternVarName(sym_ys_DOT_fs, sym_get_DASH_file_DASH_info)
	// var ys.fs/get-link-info
	var_ys_DOT_fs_get_DASH_link_DASH_info := lang.InternVarName(sym_ys_DOT_fs, sym_get_DASH_link_DASH_info)
	// var ys.fs/glob
	var_ys_DOT_fs_glob := lang.InternVarName(sym_ys_DOT_fs, sym_glob)
	// var ys.fs/l
	var_ys_DOT_fs_l := lang.InternVarName(sym_ys_DOT_fs, sym_l)
	// var ys.fs/link?
	var_ys_DOT_fs_link_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_link_QMARK_)
	// var ys.fs/ls
	var_ys_DOT_fs_ls := lang.InternVarName(sym_ys_DOT_fs, sym_ls)
	// var ys.fs/mkdir
	var_ys_DOT_fs_mkdir := lang.InternVarName(sym_ys_DOT_fs, sym_mkdir)
	// var ys.fs/mkdir-p
	var_ys_DOT_fs_mkdir_DASH_p := lang.InternVarName(sym_ys_DOT_fs, sym_mkdir_DASH_p)
	// var ys.fs/mktemp
	var_ys_DOT_fs_mktemp := lang.InternVarName(sym_ys_DOT_fs, sym_mktemp)
	// var ys.fs/mktemp-d
	var_ys_DOT_fs_mktemp_DASH_d := lang.InternVarName(sym_ys_DOT_fs, sym_mktemp_DASH_d)
	// var ys.fs/mtime
	var_ys_DOT_fs_mtime := lang.InternVarName(sym_ys_DOT_fs, sym_mtime)
	// var ys.fs/multi
	var_ys_DOT_fs_multi := lang.InternVarName(sym_ys_DOT_fs, sym_multi)
	// var ys.fs/mv
	var_ys_DOT_fs_mv := lang.InternVarName(sym_ys_DOT_fs, sym_mv)
	// var ys.fs/path
	var_ys_DOT_fs_path := lang.InternVarName(sym_ys_DOT_fs, sym_path)
	// var ys.fs/r
	var_ys_DOT_fs_r := lang.InternVarName(sym_ys_DOT_fs, sym_r)
	// var ys.fs/read
	var_ys_DOT_fs_read := lang.InternVarName(sym_ys_DOT_fs, sym_read)
	// var ys.fs/read?
	var_ys_DOT_fs_read_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_read_QMARK_)
	// var ys.fs/readlink
	var_ys_DOT_fs_readlink := lang.InternVarName(sym_ys_DOT_fs, sym_readlink)
	// var ys.fs/rel
	var_ys_DOT_fs_rel := lang.InternVarName(sym_ys_DOT_fs, sym_rel)
	// var ys.fs/rel?
	var_ys_DOT_fs_rel_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_rel_QMARK_)
	// var ys.fs/rm
	var_ys_DOT_fs_rm := lang.InternVarName(sym_ys_DOT_fs, sym_rm)
	// var ys.fs/rm-f
	var_ys_DOT_fs_rm_DASH_f := lang.InternVarName(sym_ys_DOT_fs, sym_rm_DASH_f)
	// var ys.fs/rm-r
	var_ys_DOT_fs_rm_DASH_r := lang.InternVarName(sym_ys_DOT_fs, sym_rm_DASH_r)
	// var ys.fs/rmdir
	var_ys_DOT_fs_rmdir := lang.InternVarName(sym_ys_DOT_fs, sym_rmdir)
	// var ys.fs/s
	var_ys_DOT_fs_s := lang.InternVarName(sym_ys_DOT_fs, sym_s)
	// var ys.fs/size?
	var_ys_DOT_fs_size_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_size_QMARK_)
	// var ys.fs/touch
	var_ys_DOT_fs_touch := lang.InternVarName(sym_ys_DOT_fs, sym_touch)
	// var ys.fs/w
	var_ys_DOT_fs_w := lang.InternVarName(sym_ys_DOT_fs, sym_w)
	// var ys.fs/when-str
	var_ys_DOT_fs_when_DASH_str := lang.InternVarName(sym_ys_DOT_fs, sym_when_DASH_str)
	// var ys.fs/which
	var_ys_DOT_fs_which := lang.InternVarName(sym_ys_DOT_fs, sym_which)
	// var ys.fs/write
	var_ys_DOT_fs_write := lang.InternVarName(sym_ys_DOT_fs, sym_write)
	// var ys.fs/write?
	var_ys_DOT_fs_write_QMARK_ := lang.InternVarName(sym_ys_DOT_fs, sym_write_QMARK_)
	// var ys.fs/x
	var_ys_DOT_fs_x := lang.InternVarName(sym_ys_DOT_fs, sym_x)
	// var ys.fs/z
	var_ys_DOT_fs_z := lang.InternVarName(sym_ys_DOT_fs, sym_z)
	aotExternalFn1 := aotLinkFn2(var_clojure_DOT_core__EQ_)
	aotExternalFn11 := aotLinkFn2(var_clojure_DOT_string_includes_QMARK_)
	aotExternalFn12 := aotLinkFn1(var_clojure_DOT_core_chunked_DASH_seq_QMARK_)
	aotExternalFn13 := aotLinkFn1(var_clojure_DOT_core_chunk_DASH_first)
	aotExternalFn14 := aotLinkFn1(var_clojure_DOT_core_chunk_DASH_rest)
	aotExternalFn16 := aotLinkFn1(var_clojure_DOT_core_deref)
	aotExternalFn18 := aotLinkFn1(var_clojure_DOT_core_str)
	aotExternalFn4 := aotLinkFn2(var_clojure_DOT_core_map)
	aotExternalFn5 := aotLinkFn1(var_clojure_DOT_core_not)
	aotExternalFn6 := aotLinkFn1(var_clojure_DOT_string_blank_QMARK_)
	aotExternalFn7 := aotLinkFn3(var_clojure_DOT_core_subs)
	aotExternalFn8 := aotLinkFn1(var_clojure_DOT_core_atom)
	aotExternalFn9 := aotLinkFn3(var_clojure_DOT_core_swap_BANG_)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_ys_DOT_fs)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"abs",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"empty?",
			"filter-key",
			"find",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"read",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	var closed0 any
	var closed1 any
	var closed2 any
	var closed3 any
	var closed4 any
	var closed5 any
	var closed6 any
	var closed7 any
	var closed8 any
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if path is a directory"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn18(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						tmp8, ok := lang.FieldOrMethod(v7, "IsDir")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "IsDir")))
						}
						var tmp9 any
						switch reflect.TypeOf(tmp8).Kind() {
						case reflect.Func:
							tmp9 = lang.Apply(tmp8, nil)
						default:
							tmp9 = tmp8
						}
						tmp6 = tmp9
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed0 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if path exists"
			tmp2 := aotDirectFn18(v1)
			tmp3 := lang.Identical(tmp2, nil)
			tmp4 := aotExternalFn5(tmp3)
			return tmp4
		})
		closed1 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if path is a regular file"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn18(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						var tmp8 any
						{ // let
							// let binding "mode"
							tmp9, ok := lang.FieldOrMethod(v7, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Mode")))
							}
							var tmp10 any
							switch reflect.TypeOf(tmp9).Kind() {
							case reflect.Func:
								tmp10 = lang.Apply(tmp9, nil)
							default:
								tmp10 = tmp9
							}
							var v11 any = tmp10
							_ = v11
							tmp12, ok := lang.FieldOrMethod(v11, "IsRegular")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v11, "IsRegular")))
							}
							var tmp13 any
							switch reflect.TypeOf(tmp12).Kind() {
							case reflect.Func:
								tmp13 = lang.Apply(tmp12, nil)
							default:
								tmp13 = tmp12
							}
							tmp8 = tmp13
						} // end let
						tmp6 = tmp8
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed2 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if path is a symbolic link"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn19(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						var tmp8 any
						{ // let
							// let binding "mode"
							tmp9, ok := lang.FieldOrMethod(v7, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Mode")))
							}
							var tmp10 any
							switch reflect.TypeOf(tmp9).Kind() {
							case reflect.Func:
								tmp10 = lang.Apply(tmp9, nil)
							default:
								tmp10 = tmp9
							}
							var v11 any = tmp10
							_ = v11
							// let binding "link-bit"
							tmp12 := lang.Numbers.And(v11, os5.ModeSymlink)
							var v13 any = tmp12
							_ = v13
							tmp14 := lang.Numbers.IsZero(v13)
							tmp15 := aotExternalFn5(tmp14)
							tmp8 = tmp15
						} // end let
						tmp6 = tmp8
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed3 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if path is readable"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn18(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						var tmp8 any
						{ // let
							// let binding "mode"
							tmp9, ok := lang.FieldOrMethod(v7, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Mode")))
							}
							var tmp10 any
							switch reflect.TypeOf(tmp9).Kind() {
							case reflect.Func:
								tmp10 = lang.Apply(tmp9, nil)
							default:
								tmp10 = tmp9
							}
							var v11 any = tmp10
							_ = v11
							// let binding "read-bits"
							tmp12 := lang.Numbers.And(v11, int64(292))
							var v13 any = tmp12
							_ = v13
							tmp14 := lang.Numbers.IsZero(v13)
							tmp15 := aotExternalFn5(tmp14)
							tmp8 = tmp15
						} // end let
						tmp6 = tmp8
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed4 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if file size > 0"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn18(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						tmp8, ok := lang.FieldOrMethod(v7, "Size")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Size")))
						}
						var tmp9 any
						switch reflect.TypeOf(tmp8).Kind() {
						case reflect.Func:
							tmp9 = lang.Apply(tmp8, nil)
						default:
							tmp9 = tmp8
						}
						tmp10 := lang.Numbers.Gt(tmp9, int64(0))
						tmp6 = tmp10
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed5 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if path is writable"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn18(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						var tmp8 any
						{ // let
							// let binding "mode"
							tmp9, ok := lang.FieldOrMethod(v7, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Mode")))
							}
							var tmp10 any
							switch reflect.TypeOf(tmp9).Kind() {
							case reflect.Func:
								tmp10 = lang.Apply(tmp9, nil)
							default:
								tmp10 = tmp9
							}
							var v11 any = tmp10
							_ = v11
							// let binding "write-bits"
							tmp12 := lang.Numbers.And(v11, int64(146))
							var v13 any = tmp12
							_ = v13
							tmp14 := lang.Numbers.IsZero(v13)
							tmp15 := aotExternalFn5(tmp14)
							tmp8 = tmp15
						} // end let
						tmp6 = tmp8
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed6 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if path is executable"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn18(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						var tmp8 any
						{ // let
							// let binding "mode"
							tmp9, ok := lang.FieldOrMethod(v7, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Mode")))
							}
							var tmp10 any
							switch reflect.TypeOf(tmp9).Kind() {
							case reflect.Func:
								tmp10 = lang.Apply(tmp9, nil)
							default:
								tmp10 = tmp9
							}
							var v11 any = tmp10
							_ = v11
							// let binding "exec-bits"
							tmp12 := lang.Numbers.And(v11, int64(73))
							var v13 any = tmp12
							_ = v13
							tmp14 := lang.Numbers.IsZero(v13)
							tmp15 := aotExternalFn5(tmp14)
							tmp8 = tmp15
						} // end let
						tmp6 = tmp8
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed7 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			_ = "True if file size is 0 or directory is empty"
			var tmp2 any
			{ // let
				// let binding "temp__0__auto__"
				tmp3 := aotDirectFn18(v1)
				var v4 any = tmp3
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v4) {
					var tmp6 any
					{ // let
						// let binding "info"
						var v7 any = v4
						_ = v7
						var tmp8 any
						tmp9, ok := lang.FieldOrMethod(v7, "IsDir")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "IsDir")))
						}
						var tmp10 any
						switch reflect.TypeOf(tmp9).Kind() {
						case reflect.Func:
							tmp10 = lang.Apply(tmp9, nil)
						default:
							tmp10 = tmp9
						}
						if lang.IsTruthy(tmp10) {
							var tmp11 any
							{ // let
								// let binding "entries"
								tmp12 := lang.Apply1(os5.ReadDir, v1)
								var v13 any = tmp12
								_ = v13
								tmp14 := lang.Count(v13)
								tmp15 := lang.Numbers.IsZero(tmp14)
								tmp11 = tmp15
							} // end let
							tmp8 = tmp11
						} else {
							tmp12, ok := lang.FieldOrMethod(v7, "Size")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Size")))
							}
							var tmp13 any
							switch reflect.TypeOf(tmp12).Kind() {
							case reflect.Func:
								tmp13 = lang.Apply(tmp12, nil)
							default:
								tmp13 = tmp12
							}
							tmp14 := lang.Numbers.IsZero(tmp13)
							tmp8 = tmp14
						}
						tmp6 = tmp8
					} // end let
					tmp5 = tmp6
				} else {
					tmp5 = false
				}
				tmp2 = tmp5
			} // end let
			return tmp2
		})
		closed8 = tmp0
	}
	// abs
	{
		tmp0 := sym_abs
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return absolute path"
			var tmp3 any
			{ // let
				// let binding "vec__7"
				tmp4 := lang.Apply1(filepath4.Abs, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "result"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp10 = v7
				} else {
					tmp10 = v2
				}
				tmp3 = tmp10
			} // end let
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_ys_DOT_fs_abs = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_abs.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(125), kw_column, int(7), kw_end_DASH_line, int(125), kw_end_DASH_column, int(9), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// abs?
	{
		tmp0 := sym_abs_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is absolute"
			tmp3 := lang.Apply1(filepath4.IsAbs, v2)
			return tmp3
		})
		aotDirectFn1 = tmp1
		var_ys_DOT_fs_abs_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_abs_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(38), kw_column, int(7), kw_end_DASH_line, int(38), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// basename
	{
		tmp0 := sym_basename
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return basename of path (follows symlinks)"
			var tmp3 any
			{ // let
				// let binding "vec__10"
				tmp4 := lang.Apply1(filepath4.EvalSymlinks, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "real-path"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp10 = v7
				} else {
					tmp10 = v2
				}
				tmp12 := lang.Apply1(filepath4.Base, tmp10)
				tmp3 = tmp12
			} // end let
			return tmp3
		})
		aotDirectFn2 = tmp1
		var_ys_DOT_fs_basename = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_basename.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(130), kw_column, int(7), kw_end_DASH_line, int(130), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// cp
	{
		tmp0 := sym_cp
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Copy file from src to dst"
			var tmp4 any
			{ // let
				// let binding "vec__44"
				tmp5 := lang.Apply1(os5.ReadFile, v2)
				var v6 any = tmp5
				_ = v6
				// let binding "content"
				tmp7 := runtime.RT.NthDefault(v6, lang.IntCast(int64(0)), nil)
				var v8 any = tmp7
				_ = v8
				// let binding "err"
				tmp9 := runtime.RT.NthDefault(v6, lang.IntCast(int64(1)), nil)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				tmp12 := lang.Identical(v10, nil)
				if lang.IsTruthy(tmp12) {
					tmp13 := lang.Apply3(os5.WriteFile, v3, v8, int64(420))
					tmp11 = tmp13
				} else {
				}
				tmp4 = tmp11
			} // end let
			return tmp4
		})
		aotDirectFn3 = tmp1
		var_ys_DOT_fs_cp = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_cp.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(234), kw_column, int(7), kw_end_DASH_line, int(234), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_src, sym_dst)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// cp-r
	{
		tmp0 := sym_cp_DASH_r
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Recursively copy directory"
			var tmp4 lang.FnFunc3
			tmp4 = lang.FnFunc3(func(p0, p1, p2 any) any {
				v5 := p0
				_ = v5
				v6 := p1
				_ = v6
				v7 := p2
				_ = v7
				var tmp8 any
				tmp9 := lang.Identical(v7, nil)
				if lang.IsTruthy(tmp9) {
					var tmp10 any
					{ // let
						// let binding "vec__47"
						tmp11 := lang.Apply2(filepath4.Rel, v2, v5)
						var v12 any = tmp11
						_ = v12
						// let binding "rel-path"
						tmp13 := runtime.RT.NthDefault(v12, lang.IntCast(int64(0)), nil)
						var v14 any = tmp13
						_ = v14
						// let binding "_"
						tmp15 := runtime.RT.NthDefault(v12, lang.IntCast(int64(1)), nil)
						var v16 any = tmp15
						_ = v16
						// let binding "dst-path"
						tmp17 := lang.Apply2(filepath4.Join, v3, v14)
						var v18 any = tmp17
						_ = v18
						var tmp19 any
						tmp20, ok := lang.FieldOrMethod(v6, "IsDir")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v6, "IsDir")))
						}
						var tmp21 any
						switch reflect.TypeOf(tmp20).Kind() {
						case reflect.Func:
							tmp21 = lang.Apply(tmp20, nil)
						default:
							tmp21 = tmp20
						}
						if lang.IsTruthy(tmp21) {
							tmp22 := lang.Apply2(os5.MkdirAll, v18, int64(493))
							tmp19 = tmp22
						} else {
							var tmp23 any
							{ // let
								// let binding "vec__50"
								tmp24 := lang.Apply1(os5.ReadFile, v5)
								var v25 any = tmp24
								_ = v25
								// let binding "content"
								tmp26 := runtime.RT.NthDefault(v25, lang.IntCast(int64(0)), nil)
								var v27 any = tmp26
								_ = v27
								// let binding "read-err"
								tmp28 := runtime.RT.NthDefault(v25, lang.IntCast(int64(1)), nil)
								var v29 any = tmp28
								_ = v29
								var tmp30 any
								tmp31 := lang.Identical(v29, nil)
								if lang.IsTruthy(tmp31) {
									tmp32, ok := lang.FieldOrMethod(v6, "Mode")
									if !ok {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v6, "Mode")))
									}
									var tmp33 any
									switch reflect.TypeOf(tmp32).Kind() {
									case reflect.Func:
										tmp33 = lang.Apply(tmp32, nil)
									default:
										tmp33 = tmp32
									}
									tmp34 := lang.Apply3(os5.WriteFile, v18, v27, tmp33)
									tmp30 = tmp34
								} else {
								}
								tmp23 = tmp30
							} // end let
							tmp19 = tmp23
						}
						tmp10 = tmp19
					} // end let
					tmp8 = tmp10
				} else {
				}
				_ = tmp8
				return nil
			})
			tmp5 := lang.Apply2(filepath4.Walk, v2, tmp4)
			_ = tmp5
			return nil
		})
		aotDirectFn4 = tmp1
		var_ys_DOT_fs_cp_DASH_r = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_cp_DASH_r.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(240), kw_column, int(7), kw_end_DASH_line, int(240), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_src, sym_dst)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// ctime
	{
		tmp0 := sym_ctime
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return creation time in milliseconds (same as mtime in Unix)"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						tmp9, ok := lang.FieldOrMethod(v8, "ModTime")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "ModTime")))
						}
						var tmp10 any
						switch reflect.TypeOf(tmp9).Kind() {
						case reflect.Func:
							tmp10 = lang.Apply(tmp9, nil)
						default:
							tmp10 = tmp9
						}
						tmp11, ok := lang.FieldOrMethod(tmp10, "UnixMilli")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp10, "UnixMilli")))
						}
						var tmp12 any
						switch reflect.TypeOf(tmp11).Kind() {
						case reflect.Func:
							tmp12 = lang.Apply(tmp11, nil)
						default:
							tmp12 = tmp11
						}
						tmp7 = tmp12
					} // end let
					tmp6 = tmp7
				} else {
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn5 = tmp1
		var_ys_DOT_fs_ctime = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_ctime.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(135), kw_column, int(7), kw_end_DASH_line, int(135), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// cwd
	{
		tmp0 := sym_cwd
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			_ = "Return current working directory"
			var tmp2 any
			{ // let
				// let binding "vec__13"
				tmp3 := lang.Apply0(os5.Getwd)
				var v4 any = tmp3
				_ = v4
				// let binding "result"
				tmp5 := runtime.RT.NthDefault(v4, lang.IntCast(int64(0)), nil)
				var v6 any = tmp5
				_ = v6
				// let binding "err"
				tmp7 := runtime.RT.NthDefault(v4, lang.IntCast(int64(1)), nil)
				var v8 any = tmp7
				_ = v8
				var tmp9 any
				tmp10 := lang.Identical(v8, nil)
				if lang.IsTruthy(tmp10) {
					tmp9 = v6
				} else {
					tmp9 = "."
				}
				tmp2 = tmp9
			} // end let
			return tmp2
		})
		aotDirectFn6 = tmp1
		var_ys_DOT_fs_cwd = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_cwd.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(147), kw_column, int(7), kw_end_DASH_line, int(147), kw_end_DASH_column, int(9), kw_arglists, lang.NewList(lang.NewVector()), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// d
	{
		tmp0 := sym_d
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed0, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed0, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn7 = tmp1
		var_ys_DOT_fs_d = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_d.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(111), kw_column, int(6), kw_end_DASH_line, int(111), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// dir?
	{
		tmp0 := sym_dir_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is a directory"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						tmp9, ok := lang.FieldOrMethod(v8, "IsDir")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "IsDir")))
						}
						var tmp10 any
						switch reflect.TypeOf(tmp9).Kind() {
						case reflect.Func:
							tmp10 = lang.Apply(tmp9, nil)
						default:
							tmp10 = tmp9
						}
						tmp7 = tmp10
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn8 = tmp1
		var_ys_DOT_fs_dir_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_dir_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(42), kw_column, int(7), kw_end_DASH_line, int(42), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// dirname
	{
		tmp0 := sym_dirname
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return directory name of path (follows symlinks)"
			var tmp3 any
			{ // let
				// let binding "vec__16"
				tmp4 := lang.Apply1(filepath4.EvalSymlinks, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "real-path"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp10 = v7
				} else {
					tmp10 = v2
				}
				tmp12 := lang.Apply1(filepath4.Dir, tmp10)
				tmp3 = tmp12
			} // end let
			return tmp3
		})
		aotDirectFn9 = tmp1
		var_ys_DOT_fs_dirname = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_dirname.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(152), kw_column, int(7), kw_end_DASH_line, int(152), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// e
	{
		tmp0 := sym_e
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed1, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed1, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn10 = tmp1
		var_ys_DOT_fs_e = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_e.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(112), kw_column, int(6), kw_end_DASH_line, int(112), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// empty?
	{
		tmp0 := sym_empty_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if file size is 0 or directory is empty"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						var tmp9 any
						tmp10, ok := lang.FieldOrMethod(v8, "IsDir")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "IsDir")))
						}
						var tmp11 any
						switch reflect.TypeOf(tmp10).Kind() {
						case reflect.Func:
							tmp11 = lang.Apply(tmp10, nil)
						default:
							tmp11 = tmp10
						}
						if lang.IsTruthy(tmp11) {
							var tmp12 any
							{ // let
								// let binding "entries"
								tmp13 := lang.Apply1(os5.ReadDir, v2)
								var v14 any = tmp13
								_ = v14
								tmp15 := lang.Count(v14)
								tmp16 := lang.Numbers.IsZero(tmp15)
								tmp12 = tmp16
							} // end let
							tmp9 = tmp12
						} else {
							tmp13, ok := lang.FieldOrMethod(v8, "Size")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Size")))
							}
							var tmp14 any
							switch reflect.TypeOf(tmp13).Kind() {
							case reflect.Func:
								tmp14 = lang.Apply(tmp13, nil)
							default:
								tmp14 = tmp13
							}
							tmp15 := lang.Numbers.IsZero(tmp14)
							tmp9 = tmp15
						}
						tmp7 = tmp9
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn11 = tmp1
		var_ys_DOT_fs_empty_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_empty_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(48), kw_column, int(7), kw_end_DASH_line, int(48), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// exec?
	{
		tmp0 := sym_exec_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is executable"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						var tmp9 any
						{ // let
							// let binding "mode"
							tmp10, ok := lang.FieldOrMethod(v8, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Mode")))
							}
							var tmp11 any
							switch reflect.TypeOf(tmp10).Kind() {
							case reflect.Func:
								tmp11 = lang.Apply(tmp10, nil)
							default:
								tmp11 = tmp10
							}
							var v12 any = tmp11
							_ = v12
							// let binding "exec-bits"
							tmp13 := lang.Numbers.And(v12, int64(73))
							var v14 any = tmp13
							_ = v14
							tmp15 := lang.Numbers.IsZero(v14)
							tmp16 := aotExternalFn5(tmp15)
							tmp9 = tmp16
						} // end let
						tmp7 = tmp9
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn12 = tmp1
		var_ys_DOT_fs_exec_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_exec_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(57), kw_column, int(7), kw_end_DASH_line, int(57), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// exists?
	{
		tmp0 := sym_exists_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path exists"
			tmp3 := aotDirectFn18(v2)
			tmp4 := lang.Identical(tmp3, nil)
			tmp5 := aotExternalFn5(tmp4)
			return tmp5
		})
		aotDirectFn13 = tmp1
		var_ys_DOT_fs_exists_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_exists_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(65), kw_column, int(7), kw_end_DASH_line, int(65), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// f
	{
		tmp0 := sym_f
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed2, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed2, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn14 = tmp1
		var_ys_DOT_fs_f = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_f.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(113), kw_column, int(6), kw_end_DASH_line, int(113), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// file?
	{
		tmp0 := sym_file_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is a regular file"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						var tmp9 any
						{ // let
							// let binding "mode"
							tmp10, ok := lang.FieldOrMethod(v8, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Mode")))
							}
							var tmp11 any
							switch reflect.TypeOf(tmp10).Kind() {
							case reflect.Func:
								tmp11 = lang.Apply(tmp10, nil)
							default:
								tmp11 = tmp10
							}
							var v12 any = tmp11
							_ = v12
							tmp13, ok := lang.FieldOrMethod(v12, "IsRegular")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v12, "IsRegular")))
							}
							var tmp14 any
							switch reflect.TypeOf(tmp13).Kind() {
							case reflect.Func:
								tmp14 = lang.Apply(tmp13, nil)
							default:
								tmp14 = tmp13
							}
							tmp9 = tmp14
						} // end let
						tmp7 = tmp9
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn15 = tmp1
		var_ys_DOT_fs_file_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_file_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(69), kw_column, int(7), kw_end_DASH_line, int(69), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// filename
	{
		tmp0 := sym_filename
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return filename without extension"
			var tmp3 any
			{ // let
				// let binding "base"
				tmp4 := lang.Apply1(filepath4.Base, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "ext"
				tmp6 := lang.Apply1(filepath4.Ext, v5)
				var v7 any = tmp6
				_ = v7
				var tmp8 any
				tmp9 := aotExternalFn6(v7)
				if lang.IsTruthy(tmp9) {
					tmp8 = v5
				} else {
					tmp10 := lang.Count(v5)
					tmp11 := lang.Count(v7)
					tmp12 := lang.Numbers.Minus(tmp10, tmp11)
					tmp13 := aotExternalFn7(v5, int64(0), tmp12)
					tmp8 = tmp13
				}
				tmp3 = tmp8
			} // end let
			return tmp3
		})
		aotDirectFn16 = tmp1
		var_ys_DOT_fs_filename = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_filename.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(157), kw_column, int(7), kw_end_DASH_line, int(157), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// get-file-info
	{
		tmp0 := sym_get_DASH_file_DASH_info
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Get os.FileInfo for path, returns nil on error"
			var tmp3 any
			func() {
				defer func() {
					if r := recover(); r != nil {
						if lang.CatchMatches(r, lang.Builtins["any"]) {
							v4 := r
							_ = v4
						} else {
							panic(r)
						}
					}
				}()
				var tmp4 any
				{ // let
					// let binding "vec__1"
					tmp5 := lang.Apply1(os5.Stat, v2)
					var v6 any = tmp5
					_ = v6
					// let binding "info"
					tmp7 := runtime.RT.NthDefault(v6, lang.IntCast(int64(0)), nil)
					var v8 any = tmp7
					_ = v8
					// let binding "err"
					tmp9 := runtime.RT.NthDefault(v6, lang.IntCast(int64(1)), nil)
					var v10 any = tmp9
					_ = v10
					var tmp11 any
					tmp12 := lang.Identical(v10, nil)
					if lang.IsTruthy(tmp12) {
						tmp11 = v8
					} else {
					}
					tmp4 = tmp11
				} // end let
				tmp3 = tmp4
			}()
			return tmp3
		})
		aotDirectFn18 = tmp1
		var_ys_DOT_fs_get_DASH_file_DASH_info = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_get_DASH_file_DASH_info.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/fs.glj", kw_line, int(20), kw_column, int(8), kw_end_DASH_line, int(20), kw_end_DASH_column, int(20), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// get-link-info
	{
		tmp0 := sym_get_DASH_link_DASH_info
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Get os.FileInfo for symlink (don't follow), returns nil on error"
			var tmp3 any
			func() {
				defer func() {
					if r := recover(); r != nil {
						if lang.CatchMatches(r, lang.Builtins["any"]) {
							v4 := r
							_ = v4
						} else {
							panic(r)
						}
					}
				}()
				var tmp4 any
				{ // let
					// let binding "vec__4"
					tmp5 := lang.Apply1(os5.Lstat, v2)
					var v6 any = tmp5
					_ = v6
					// let binding "info"
					tmp7 := runtime.RT.NthDefault(v6, lang.IntCast(int64(0)), nil)
					var v8 any = tmp7
					_ = v8
					// let binding "err"
					tmp9 := runtime.RT.NthDefault(v6, lang.IntCast(int64(1)), nil)
					var v10 any = tmp9
					_ = v10
					var tmp11 any
					tmp12 := lang.Identical(v10, nil)
					if lang.IsTruthy(tmp12) {
						tmp11 = v8
					} else {
					}
					tmp4 = tmp11
				} // end let
				tmp3 = tmp4
			}()
			return tmp3
		})
		aotDirectFn19 = tmp1
		var_ys_DOT_fs_get_DASH_link_DASH_info = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_get_DASH_link_DASH_info.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/fs.glj", kw_line, int(27), kw_column, int(8), kw_end_DASH_line, int(27), kw_end_DASH_column, int(20), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// glob
	{
		tmp0 := sym_glob
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return paths matching glob pattern"
			var tmp3 any
			{ // let
				// let binding "vec__23"
				tmp4 := lang.Apply1(filepath4.Glob, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "result"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp10 = v7
				} else {
					tmp12 := lang.NewVector()
					tmp10 = tmp12
				}
				tmp3 = tmp10
			} // end let
			return tmp3
		})
		aotDirectFn20 = tmp1
		var_ys_DOT_fs_glob = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_glob.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(180), kw_column, int(7), kw_end_DASH_line, int(180), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_pattern)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// l
	{
		tmp0 := sym_l
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed3, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed3, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn21 = tmp1
		var_ys_DOT_fs_l = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_l.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(114), kw_column, int(6), kw_end_DASH_line, int(114), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// link?
	{
		tmp0 := sym_link_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is a symbolic link"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn19(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						var tmp9 any
						{ // let
							// let binding "mode"
							tmp10, ok := lang.FieldOrMethod(v8, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Mode")))
							}
							var tmp11 any
							switch reflect.TypeOf(tmp10).Kind() {
							case reflect.Func:
								tmp11 = lang.Apply(tmp10, nil)
							default:
								tmp11 = tmp10
							}
							var v12 any = tmp11
							_ = v12
							// let binding "link-bit"
							tmp13 := lang.Numbers.And(v12, os5.ModeSymlink)
							var v14 any = tmp13
							_ = v14
							tmp15 := lang.Numbers.IsZero(v14)
							tmp16 := aotExternalFn5(tmp15)
							tmp9 = tmp16
						} // end let
						tmp7 = tmp9
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn22 = tmp1
		var_ys_DOT_fs_link_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_link_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(76), kw_column, int(7), kw_end_DASH_line, int(76), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// ls
	{
		tmp0 := sym_ls
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "List directory contents"
			var tmp3 any
			{ // let
				// let binding "vec__26"
				tmp4 := lang.Apply1(os5.ReadDir, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "entries"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					var tmp12 any
					{ // let
						// let binding "i"
						var v13 any = int64(0)
						_ = v13
						// let binding "n"
						tmp14 := lang.Count(v7)
						var v15 any = tmp14
						_ = v15
						// let binding "result"
						tmp16 := lang.NewVector()
						var v17 any = tmp16
						_ = v17
						for {
							var tmp18 any
							tmp19 := lang.Numbers.Lt(v13, v15)
							if lang.IsTruthy(tmp19) {
								tmp21 := lang.Numbers.Inc(v13)
								var tmp20 any = tmp21
								var tmp22 any = v15
								tmp24 := runtime.RT.Nth(v7, lang.IntCast(v13))
								tmp25, ok := lang.FieldOrMethod(tmp24, "Name")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp24, "Name")))
								}
								var tmp26 any
								switch reflect.TypeOf(tmp25).Kind() {
								case reflect.Func:
									tmp26 = lang.Apply(tmp25, nil)
								default:
									tmp26 = tmp25
								}
								tmp27 := lang.ConjAny(v17, tmp26)
								var tmp23 any = tmp27
								v13 = tmp20
								v15 = tmp22
								v17 = tmp23
								continue
							} else {
								tmp18 = v17
							}
							tmp12 = tmp18
							break
						}
					} // end let
					tmp10 = tmp12
				} else {
					tmp13 := lang.NewVector()
					tmp10 = tmp13
				}
				tmp3 = tmp10
			} // end let
			return tmp3
		})
		aotDirectFn23 = tmp1
		var_ys_DOT_fs_ls = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_ls.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(185), kw_column, int(7), kw_end_DASH_line, int(185), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// mkdir
	{
		tmp0 := sym_mkdir
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Create directory"
			tmp3 := lang.Apply2(os5.Mkdir, v2, int64(493))
			return tmp3
		})
		aotDirectFn24 = tmp1
		var_ys_DOT_fs_mkdir = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_mkdir.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(256), kw_column, int(7), kw_end_DASH_line, int(256), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// mkdir-p
	{
		tmp0 := sym_mkdir_DASH_p
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Create directory and parents"
			tmp3 := lang.Apply2(os5.MkdirAll, v2, int64(493))
			return tmp3
		})
		aotDirectFn25 = tmp1
		var_ys_DOT_fs_mkdir_DASH_p = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_mkdir_DASH_p.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(260), kw_column, int(7), kw_end_DASH_line, int(260), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// mktemp
	{
		tmp0 := sym_mktemp
		var tmp1 lang.ArityFn
		aotDirectFn26Arity0 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn26Arity2("", "ys-")
			return tmp2
		})
		aotDirectFn26Arity1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotDirectFn26Arity2("", v2)
			return tmp3
		})
		aotDirectFn26Arity2 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "vec__56"
				tmp5 := lang.Apply2(os5.CreateTemp, v2, v3)
				var v6 any = tmp5
				_ = v6
				// let binding "f"
				tmp7 := runtime.RT.NthDefault(v6, lang.IntCast(int64(0)), nil)
				var v8 any = tmp7
				_ = v8
				// let binding "err"
				tmp9 := runtime.RT.NthDefault(v6, lang.IntCast(int64(1)), nil)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				tmp12 := lang.Identical(v10, nil)
				if lang.IsTruthy(tmp12) {
					tmp13, ok := lang.FieldOrMethod(v8, "Close")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Close")))
					}
					var tmp14 any
					switch reflect.TypeOf(tmp13).Kind() {
					case reflect.Func:
						tmp14 = lang.Apply(tmp13, nil)
					default:
						tmp14 = tmp13
					}
					_ = tmp14
					tmp15, ok := lang.FieldOrMethod(v8, "Name")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Name")))
					}
					var tmp16 any
					switch reflect.TypeOf(tmp15).Kind() {
					case reflect.Func:
						tmp16 = lang.Apply(tmp15, nil)
					default:
						tmp16 = tmp15
					}
					tmp17 := aotExternalFn18(tmp16)
					tmp11 = tmp17
				} else {
				}
				tmp4 = tmp11
			} // end let
			return tmp4
		})
		tmp1 = lang.NewArityFn(
			aotDirectFn26Arity0,
			aotDirectFn26Arity1,
			aotDirectFn26Arity2,
			nil,
			nil,
			nil,
			0,
		)
		aotDirectFn26 = tmp1
		var_ys_DOT_fs_mktemp = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_mktemp.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/fs.glj", kw_line, int(295), kw_column, int(7), kw_end_DASH_line, int(295), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_prefix), lang.NewVector(sym_dir, sym_prefix)), kw_doc, "Create temporary file and return path", kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// mktemp-d
	{
		tmp0 := sym_mktemp_DASH_d
		var tmp1 lang.ArityFn
		aotDirectFn27Arity0 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn27Arity2("", "ys-")
			return tmp2
		})
		aotDirectFn27Arity1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotDirectFn27Arity2("", v2)
			return tmp3
		})
		aotDirectFn27Arity2 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "vec__59"
				tmp5 := lang.Apply2(os5.MkdirTemp, v2, v3)
				var v6 any = tmp5
				_ = v6
				// let binding "path"
				tmp7 := runtime.RT.NthDefault(v6, lang.IntCast(int64(0)), nil)
				var v8 any = tmp7
				_ = v8
				// let binding "err"
				tmp9 := runtime.RT.NthDefault(v6, lang.IntCast(int64(1)), nil)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				tmp12 := lang.Identical(v10, nil)
				if lang.IsTruthy(tmp12) {
					tmp11 = v8
				} else {
				}
				tmp4 = tmp11
			} // end let
			return tmp4
		})
		tmp1 = lang.NewArityFn(
			aotDirectFn27Arity0,
			aotDirectFn27Arity1,
			aotDirectFn27Arity2,
			nil,
			nil,
			nil,
			0,
		)
		aotDirectFn27 = tmp1
		var_ys_DOT_fs_mktemp_DASH_d = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_mktemp_DASH_d.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/fs.glj", kw_line, int(305), kw_column, int(7), kw_end_DASH_line, int(305), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_prefix), lang.NewVector(sym_dir, sym_prefix)), kw_doc, "Create temporary directory and return path", kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// mtime
	{
		tmp0 := sym_mtime
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return modification time in milliseconds"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						tmp9, ok := lang.FieldOrMethod(v8, "ModTime")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "ModTime")))
						}
						var tmp10 any
						switch reflect.TypeOf(tmp9).Kind() {
						case reflect.Func:
							tmp10 = lang.Apply(tmp9, nil)
						default:
							tmp10 = tmp9
						}
						tmp11, ok := lang.FieldOrMethod(tmp10, "UnixMilli")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp10, "UnixMilli")))
						}
						var tmp12 any
						switch reflect.TypeOf(tmp11).Kind() {
						case reflect.Func:
							tmp12 = lang.Apply(tmp11, nil)
						default:
							tmp12 = tmp11
						}
						tmp7 = tmp12
					} // end let
					tmp6 = tmp7
				} else {
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn28 = tmp1
		var_ys_DOT_fs_mtime = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_mtime.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(141), kw_column, int(7), kw_end_DASH_line, int(141), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// multi
	{
		tmp0 := sym_multi
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Wrap single-path function to support multiple paths"
			var tmp3 lang.ArityFn
			tmp3 = lang.NewArityFn(
				nil,
				nil,
				nil,
				nil,
				nil,
				lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
					var v4 any = rest
					_ = v4
					var tmp5 any
					tmp6 := lang.Count(v4)
					tmp7 := aotExternalFn1(int64(1), tmp6)
					if lang.IsTruthy(tmp7) {
						tmp8 := lang.First(v4)
						tmp9 := lang.Apply1(v2, tmp8)
						tmp5 = tmp9
					} else {
						tmp10 := aotExternalFn4(v2, v4)
						tmp5 = tmp10
					}
					return tmp5
				}),
				0,
			)
			return tmp3
		})
		aotDirectFn29 = tmp1
		var_ys_DOT_fs_multi = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_multi.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/fs.glj", kw_line, int(13), kw_column, int(8), kw_end_DASH_line, int(13), kw_end_DASH_column, int(12), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_f)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// mv
	{
		tmp0 := sym_mv
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Move/rename file or directory"
			tmp4 := lang.Apply2(os5.Rename, v2, v3)
			return tmp4
		})
		aotDirectFn30 = tmp1
		var_ys_DOT_fs_mv = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_mv.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(264), kw_column, int(7), kw_end_DASH_line, int(264), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_src, sym_dst)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// path
	{
		tmp0 := sym_path
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return canonical path (follows symlinks)"
			var tmp3 any
			{ // let
				// let binding "vec__29"
				tmp4 := lang.Apply1(filepath4.EvalSymlinks, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "result"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp10 = v7
				} else {
					tmp10 = v2
				}
				tmp3 = tmp10
			} // end let
			return tmp3
		})
		aotDirectFn31 = tmp1
		var_ys_DOT_fs_path = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_path.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(195), kw_column, int(7), kw_end_DASH_line, int(195), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_p)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// r
	{
		tmp0 := sym_r
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed4, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed4, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn32 = tmp1
		var_ys_DOT_fs_r = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_r.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(115), kw_column, int(6), kw_end_DASH_line, int(115), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// read
	{
		tmp0 := sym_read
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Read file contents as string"
			var tmp3 any
			{ // let
				// let binding "vec__41"
				tmp4 := lang.Apply1(os5.ReadFile, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "bytes"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp12 := lang.Apply2(fmt.Sprintf, "%s", v7)
					tmp10 = tmp12
				} else {
					tmp13, ok := pkgmap6.Get("util.die")
					if !ok {
						panic(lang.NewIllegalArgumentError("unable to resolve host form: util.die"))
					}
					tmp14 := lang.Apply2(tmp13, "Failed to read file: ", v2)
					tmp10 = tmp14
				}
				tmp3 = tmp10
			} // end let
			return tmp3
		})
		aotDirectFn33 = tmp1
		var_ys_DOT_fs_read = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_read.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(216), kw_column, int(7), kw_end_DASH_line, int(216), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// read?
	{
		tmp0 := sym_read_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is readable"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						var tmp9 any
						{ // let
							// let binding "mode"
							tmp10, ok := lang.FieldOrMethod(v8, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Mode")))
							}
							var tmp11 any
							switch reflect.TypeOf(tmp10).Kind() {
							case reflect.Func:
								tmp11 = lang.Apply(tmp10, nil)
							default:
								tmp11 = tmp10
							}
							var v12 any = tmp11
							_ = v12
							// let binding "read-bits"
							tmp13 := lang.Numbers.And(v12, int64(292))
							var v14 any = tmp13
							_ = v14
							tmp15 := lang.Numbers.IsZero(v14)
							tmp16 := aotExternalFn5(tmp15)
							tmp9 = tmp16
						} // end let
						tmp7 = tmp9
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn34 = tmp1
		var_ys_DOT_fs_read_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_read_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(84), kw_column, int(7), kw_end_DASH_line, int(84), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// readlink
	{
		tmp0 := sym_readlink
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Read symbolic link target"
			var tmp3 any
			{ // let
				// let binding "vec__32"
				tmp4 := lang.Apply1(os5.Readlink, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "result"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp10 = v7
				} else {
				}
				tmp3 = tmp10
			} // end let
			return tmp3
		})
		aotDirectFn35 = tmp1
		var_ys_DOT_fs_readlink = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_readlink.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(200), kw_column, int(7), kw_end_DASH_line, int(200), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// rel
	{
		tmp0 := sym_rel
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Return path relative to current directory"
			var tmp3 any
			{ // let
				// let binding "cwd-path"
				tmp4 := aotDirectFn6()
				var v5 any = tmp4
				_ = v5
				// let binding "vec__35"
				tmp6 := lang.Apply2(filepath4.Rel, v5, v2)
				var v7 any = tmp6
				_ = v7
				// let binding "result"
				tmp8 := runtime.RT.NthDefault(v7, lang.IntCast(int64(0)), nil)
				var v9 any = tmp8
				_ = v9
				// let binding "err"
				tmp10 := runtime.RT.NthDefault(v7, lang.IntCast(int64(1)), nil)
				var v11 any = tmp10
				_ = v11
				var tmp12 any
				tmp13 := lang.Identical(v11, nil)
				if lang.IsTruthy(tmp13) {
					tmp12 = v9
				} else {
					tmp12 = v2
				}
				tmp3 = tmp12
			} // end let
			return tmp3
		})
		aotDirectFn36 = tmp1
		var_ys_DOT_fs_rel = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_rel.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(205), kw_column, int(7), kw_end_DASH_line, int(205), kw_end_DASH_column, int(9), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// rel?
	{
		tmp0 := sym_rel_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is relative"
			tmp3 := lang.Apply1(filepath4.IsAbs, v2)
			tmp4 := aotExternalFn5(tmp3)
			return tmp4
		})
		aotDirectFn37 = tmp1
		var_ys_DOT_fs_rel_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_rel_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(92), kw_column, int(7), kw_end_DASH_line, int(92), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// rm
	{
		tmp0 := sym_rm
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Remove file or empty directory"
			tmp3 := lang.Apply1(os5.Remove, v2)
			return tmp3
		})
		aotDirectFn38 = tmp1
		var_ys_DOT_fs_rm = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_rm.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(268), kw_column, int(7), kw_end_DASH_line, int(268), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// rm-f
	{
		tmp0 := sym_rm_DASH_f
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Remove file, ignore errors"
			var tmp3 any
			func() {
				defer func() {
					if r := recover(); r != nil {
						if lang.CatchMatches(r, lang.Builtins["any"]) {
							v4 := r
							_ = v4
						} else {
							panic(r)
						}
					}
				}()
				tmp4 := lang.Apply1(os5.Remove, v2)
				tmp3 = tmp4
			}()
			return tmp3
		})
		aotDirectFn39 = tmp1
		var_ys_DOT_fs_rm_DASH_f = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_rm_DASH_f.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(272), kw_column, int(7), kw_end_DASH_line, int(272), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// rm-r
	{
		tmp0 := sym_rm_DASH_r
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Remove directory recursively"
			tmp3 := lang.Apply1(os5.RemoveAll, v2)
			return tmp3
		})
		aotDirectFn40 = tmp1
		var_ys_DOT_fs_rm_DASH_r = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_rm_DASH_r.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(278), kw_column, int(7), kw_end_DASH_line, int(278), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// rmdir
	{
		tmp0 := sym_rmdir
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Remove empty directory"
			tmp3 := lang.Apply1(os5.Remove, v2)
			return tmp3
		})
		aotDirectFn41 = tmp1
		var_ys_DOT_fs_rmdir = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_rmdir.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(282), kw_column, int(7), kw_end_DASH_line, int(282), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// s
	{
		tmp0 := sym_s
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed5, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed5, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn42 = tmp1
		var_ys_DOT_fs_s = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_s.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(116), kw_column, int(6), kw_end_DASH_line, int(116), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// size?
	{
		tmp0 := sym_size_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if file size > 0"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						tmp9, ok := lang.FieldOrMethod(v8, "Size")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Size")))
						}
						var tmp10 any
						switch reflect.TypeOf(tmp9).Kind() {
						case reflect.Func:
							tmp10 = lang.Apply(tmp9, nil)
						default:
							tmp10 = tmp9
						}
						tmp11 := lang.Numbers.Gt(tmp10, int64(0))
						tmp7 = tmp11
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn43 = tmp1
		var_ys_DOT_fs_size_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_size_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(96), kw_column, int(7), kw_end_DASH_line, int(96), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// touch
	{
		tmp0 := sym_touch
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Update file timestamp or create if doesn't exist"
			var tmp3 any
			tmp4 := aotDirectFn13(v2)
			if lang.IsTruthy(tmp4) {
				var tmp5 any
				{ // let
					// let binding "now"
					tmp6 := time7.Now()
					var v7 any = tmp6
					_ = v7
					tmp8 := lang.Apply3(os5.Chtimes, v2, v7, v7)
					tmp5 = tmp8
				} // end let
				tmp3 = tmp5
			} else {
				var tmp6 any
				{ // let
					// let binding "vec__53"
					tmp7 := lang.Apply1(os5.Create, v2)
					var v8 any = tmp7
					_ = v8
					// let binding "f"
					tmp9 := runtime.RT.NthDefault(v8, lang.IntCast(int64(0)), nil)
					var v10 any = tmp9
					_ = v10
					// let binding "err"
					tmp11 := runtime.RT.NthDefault(v8, lang.IntCast(int64(1)), nil)
					var v12 any = tmp11
					_ = v12
					var tmp13 any
					tmp14 := lang.Identical(v12, nil)
					if lang.IsTruthy(tmp14) {
						tmp15, ok := lang.FieldOrMethod(v10, "Close")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v10, "Close")))
						}
						var tmp16 any
						switch reflect.TypeOf(tmp15).Kind() {
						case reflect.Func:
							tmp16 = lang.Apply(tmp15, nil)
						default:
							tmp16 = tmp15
						}
						tmp13 = tmp16
					} else {
					}
					tmp6 = tmp13
				} // end let
				tmp3 = tmp6
			}
			return tmp3
		})
		aotDirectFn44 = tmp1
		var_ys_DOT_fs_touch = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_touch.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(286), kw_column, int(7), kw_end_DASH_line, int(286), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// w
	{
		tmp0 := sym_w
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed6, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed6, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn45 = tmp1
		var_ys_DOT_fs_w = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_w.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(117), kw_column, int(6), kw_end_DASH_line, int(117), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// when-str
	{
		tmp0 := sym_when_DASH_str
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Convert to string or return nil"
			var tmp3 any
			if lang.IsTruthy(v2) {
				tmp4 := aotExternalFn18(v2)
				tmp3 = tmp4
			} else {
			}
			return tmp3
		})
		aotDirectFn46 = tmp1
		var_ys_DOT_fs_when_DASH_str = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_when_DASH_str.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/fs.glj", kw_line, int(9), kw_column, int(8), kw_end_DASH_line, int(9), kw_end_DASH_column, int(15), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// which
	{
		tmp0 := sym_which
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Find executable in PATH"
			var tmp3 any
			{ // let
				// let binding "vec__38"
				tmp4 := lang.Apply1(exec8.LookPath, v2)
				var v5 any = tmp4
				_ = v5
				// let binding "result"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
					tmp10 = v7
				} else {
				}
				tmp3 = tmp10
			} // end let
			return tmp3
		})
		aotDirectFn47 = tmp1
		var_ys_DOT_fs_which = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_which.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(211), kw_column, int(7), kw_end_DASH_line, int(211), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_name)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// write
	{
		tmp0 := sym_write
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Write string content to file"
			var tmp4 any
			{ // let
				// let binding "bytes"
				tmp5, ok := lang.FieldOrMethod(v3, "getBytes")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v3, "getBytes")))
				}
				var tmp6 any
				switch reflect.TypeOf(tmp5).Kind() {
				case reflect.Func:
					tmp6 = lang.Apply(tmp5, nil)
				default:
					tmp6 = tmp5
				}
				var v7 any = tmp6
				_ = v7
				// let binding "err"
				tmp8 := lang.Apply3(os5.WriteFile, v2, v7, int64(420))
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				tmp11 := lang.Identical(v9, nil)
				if lang.IsTruthy(tmp11) {
				} else {
					tmp12, ok := pkgmap6.Get("util.die")
					if !ok {
						panic(lang.NewIllegalArgumentError("unable to resolve host form: util.die"))
					}
					tmp13 := lang.Apply2(tmp12, "Failed to write file: ", v2)
					tmp10 = tmp13
				}
				tmp4 = tmp10
			} // end let
			return tmp4
		})
		aotDirectFn48 = tmp1
		var_ys_DOT_fs_write = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_write.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(223), kw_column, int(7), kw_end_DASH_line, int(223), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_path, sym_content)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// write?
	{
		tmp0 := sym_write_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "True if path is writable"
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					var tmp7 any
					{ // let
						// let binding "info"
						var v8 any = v5
						_ = v8
						var tmp9 any
						{ // let
							// let binding "mode"
							tmp10, ok := lang.FieldOrMethod(v8, "Mode")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Mode")))
							}
							var tmp11 any
							switch reflect.TypeOf(tmp10).Kind() {
							case reflect.Func:
								tmp11 = lang.Apply(tmp10, nil)
							default:
								tmp11 = tmp10
							}
							var v12 any = tmp11
							_ = v12
							// let binding "write-bits"
							tmp13 := lang.Numbers.And(v12, int64(146))
							var v14 any = tmp13
							_ = v14
							tmp15 := lang.Numbers.IsZero(v14)
							tmp16 := aotExternalFn5(tmp15)
							tmp9 = tmp16
						} // end let
						tmp7 = tmp9
					} // end let
					tmp6 = tmp7
				} else {
					tmp6 = false
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn49 = tmp1
		var_ys_DOT_fs_write_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_write_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(102), kw_column, int(7), kw_end_DASH_line, int(102), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_path)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// x
	{
		tmp0 := sym_x
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed7, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed7, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn50 = tmp1
		var_ys_DOT_fs_x = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_x.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(118), kw_column, int(6), kw_end_DASH_line, int(118), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// z
	{
		tmp0 := sym_z
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				tmp4 := lang.Count(v2)
				tmp5 := aotExternalFn1(int64(1), tmp4)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.First(v2)
					tmp7 := lang.Apply1(closed8, tmp6)
					tmp3 = tmp7
				} else {
					tmp8 := aotExternalFn4(closed8, v2)
					tmp3 = tmp8
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn51 = tmp1
		var_ys_DOT_fs_z = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_z.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(119), kw_column, int(6), kw_end_DASH_line, int(119), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
	// find
	{
		tmp0 := sym_find
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				var v3 any = rest
				_ = v3
				_ = "Walk directory tree and return matching paths"
				var tmp4 any
				{ // let
					// let binding "results"
					tmp5 := lang.NewVector()
					tmp6 := aotExternalFn8(tmp5)
					var v7 any = tmp6
					_ = v7
					var tmp8 lang.FnFunc3
					tmp8 = lang.FnFunc3(func(p0, p1, p2 any) any {
						v9 := p0
						_ = v9
						v10 := p1
						_ = v10
						v11 := p2
						_ = v11
						var tmp12 any
						tmp13 := lang.Identical(v11, nil)
						if lang.IsTruthy(tmp13) {
							var tmp14 any
							tmp15 := aotDirectFn11(v3)
							if lang.IsTruthy(tmp15) {
								tmp16 := checkDerefVar(var_clojure_DOT_core_conj)
								tmp17 := aotExternalFn9(v7, tmp16, v9)
								tmp14 = tmp17
							} else {
								var tmp18 any
								{ // let
									// let binding "seq_19"
									tmp19 := lang.Seq(v3)
									var v20 any = tmp19
									_ = v20
									// let binding "chunk_20"
									var v21 any = nil
									_ = v21
									// let binding "count_21"
									var v22 any = int64(0)
									_ = v22
									// let binding "i_22"
									var v23 any = int64(0)
									_ = v23
									for {
										var tmp24 any
										tmp25 := lang.Numbers.Lt(v23, v22)
										if lang.IsTruthy(tmp25) {
											var tmp26 any
											{ // let
												// let binding "pattern"
												tmp27 := v21.(interface{ Nth(int) any }).Nth(lang.IntCast(v23))
												var v28 any = tmp27
												_ = v28
												var tmp29 any
												tmp30 := aotExternalFn11(v9, v28)
												if lang.IsTruthy(tmp30) {
													tmp31 := checkDerefVar(var_clojure_DOT_core_conj)
													tmp32 := aotExternalFn9(v7, tmp31, v9)
													tmp29 = tmp32
												} else {
												}
												_ = tmp29
												var tmp33 any = v20
												var tmp34 any = v21
												var tmp35 any = v22
												tmp37 := lang.Numbers.Unchecked_inc(v23)
												var tmp36 any = tmp37
												v20 = tmp33
												v21 = tmp34
												v22 = tmp35
												v23 = tmp36
												continue
											} // end let
											tmp24 = tmp26
										} else {
											var tmp27 any
											{ // let
												// let binding "temp__0__auto__"
												tmp28 := lang.Seq(v20)
												var v29 any = tmp28
												_ = v29
												var tmp30 any
												if lang.IsTruthy(v29) {
													var tmp31 any
													{ // let
														// let binding "seq_19"
														var v32 any = v29
														_ = v32
														var tmp33 any
														tmp34 := aotExternalFn12(v32)
														if lang.IsTruthy(tmp34) {
															var tmp35 any
															{ // let
																// let binding "c__0__auto__"
																tmp36 := aotExternalFn13(v32)
																var v37 any = tmp36
																_ = v37
																tmp39 := aotExternalFn14(v32)
																var tmp38 any = tmp39
																var tmp40 any = v37
																tmp42 := lang.Count(v37)
																tmp43 := runtime.RT.IntCast(tmp42)
																var tmp41 any = tmp43
																tmp45 := runtime.RT.IntCast(int64(0))
																var tmp44 any = tmp45
																v20 = tmp38
																v21 = tmp40
																v22 = tmp41
																v23 = tmp44
																continue
															} // end let
															tmp33 = tmp35
														} else {
															var tmp36 any
															{ // let
																// let binding "pattern"
																tmp37 := lang.First(v32)
																var v38 any = tmp37
																_ = v38
																var tmp39 any
																tmp40 := aotExternalFn11(v9, v38)
																if lang.IsTruthy(tmp40) {
																	tmp41 := checkDerefVar(var_clojure_DOT_core_conj)
																	tmp42 := aotExternalFn9(v7, tmp41, v9)
																	tmp39 = tmp42
																} else {
																}
																_ = tmp39
																tmp44 := lang.Next(v32)
																var tmp43 any = tmp44
																var tmp45 any = nil
																var tmp46 any = int64(0)
																var tmp47 any = int64(0)
																v20 = tmp43
																v21 = tmp45
																v22 = tmp46
																v23 = tmp47
																continue
															} // end let
															tmp33 = tmp36
														}
														tmp31 = tmp33
													} // end let
													tmp30 = tmp31
												} else {
												}
												tmp27 = tmp30
											} // end let
											tmp24 = tmp27
										}
										tmp18 = tmp24
										break
									}
								} // end let
								tmp14 = tmp18
							}
							tmp12 = tmp14
						} else {
						}
						_ = tmp12
						return nil
					})
					tmp9 := lang.Apply2(filepath4.Walk, v2, tmp8)
					_ = tmp9
					tmp10 := aotExternalFn16(v7)
					tmp4 = tmp10
				} // end let
				return tmp4
			}),
			1,
		)
		aotDirectFn17 = tmp1
		var_ys_DOT_fs_find = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_fs_find.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/fs.glj", kw_line, int(165), kw_column, int(7), kw_end_DASH_line, int(165), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_path, sym__AMP_, sym_patterns)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_fs))
		})
	}
}
