// Code generated by glojure codegen. DO NOT EDIT.

package v0

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	regexp4 "regexp"
)

func init() {
	runtime.RegisterNSLoader("ys/v0", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "ys.v0"
func LoadNS() {
	sym_args := lang.NewSymbol("args")
	sym_clojure_DOT_core := lang.NewSymbol("clojure.core")
	sym_map_DASH_parse := lang.NewSymbol("map-parse")
	sym_mapv := lang.NewSymbol("mapv")
	sym_re_DASH_matches := lang.NewSymbol("re-matches")
	sym_read_DASH_string := lang.NewSymbol("read-string")
	sym_ys_DOT_v0 := lang.NewSymbol("ys.v0")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_rettag := lang.NewKeyword("rettag")
	// var clojure.core/mapv
	var_clojure_DOT_core_mapv := lang.InternVarName(sym_clojure_DOT_core, sym_mapv)
	// var clojure.core/re-matches
	var_clojure_DOT_core_re_DASH_matches := lang.InternVarName(sym_clojure_DOT_core, sym_re_DASH_matches)
	// var clojure.core/read-string
	var_clojure_DOT_core_read_DASH_string := lang.InternVarName(sym_clojure_DOT_core, sym_read_DASH_string)
	// var ys.v0/map-parse
	var_ys_DOT_v0_map_DASH_parse := lang.InternVarName(sym_ys_DOT_v0, sym_map_DASH_parse)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_ys_DOT_v0)
	_ = ns
	// map-parse
	{
		tmp0 := sym_map_DASH_parse.WithMeta(lang.NewMap(kw_file, "ys/v0.glj", kw_line, int(15), kw_column, int(7), kw_end_DASH_line, int(15), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_v0))).(*lang.Symbol)
		var tmp1 lang.FnFunc
		tmp1 = lang.NewFnFunc(func(args ...any) any {
			checkArity(args, 1)
			v2 := args[0]
			_ = v2
			tmp3 := checkDerefVar(var_clojure_DOT_core_mapv)
			var tmp4 lang.FnFunc
			tmp4 = lang.NewFnFunc(func(args ...any) any {
				checkArity(args, 1)
				v5 := args[0]
				_ = v5
				var tmp6 any
				tmp7 := checkDerefVar(var_clojure_DOT_core_re_DASH_matches)
				tmp8 := lang.Apply(tmp7, []any{regexp4.MustCompile("^[+-]?[0-9]+\\.?[0-9]*([eE][+-]?[0-9]+)?$"), v5})
				if lang.IsTruthy(tmp8) {
					tmp9 := checkDerefVar(var_clojure_DOT_core_read_DASH_string)
					tmp10 := lang.Apply(tmp9, []any{v5})
					tmp6 = tmp10
				} else {
					tmp6 = v5
				}
				return tmp6
			})
			tmp5 := lang.NewMap(kw_file, "ys/v0.glj", kw_line, int(17), kw_column, int(5), kw_end_DASH_line, int(20), kw_end_DASH_column, int(11))
			tmp6, err := lang.WithMeta(tmp4, tmp5.(lang.IPersistentMap))
			if err != nil {
				panic(err)
			}
			tmp7 := lang.Apply(tmp3, []any{tmp6, v2})
			return tmp7
		})
		tmp1 = tmp1.WithMeta(lang.NewMap(kw_rettag, nil)).(lang.FnFunc)
		var_ys_DOT_v0_map_DASH_parse = ns.InternWithValue(tmp0, tmp1, true)
		if tmp0.Meta() != nil {
			var_ys_DOT_v0_map_DASH_parse.SetMeta(tmp0.Meta().(lang.IPersistentMap))
		}
	}
}
