// Code generated by glojure codegen. DO NOT EDIT.

package common

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	regexp4 "regexp"
)

var aotDirectFn0 lang.FnFunc1
var aotRootVersion0 *lang.VarRootVersion
var aotDirectFn1 lang.FnFunc2
var aotRootVersion1 *lang.VarRootVersion
var aotDirectFn2 lang.FnFunc1
var aotRootVersion2 *lang.VarRootVersion

func init() {
	runtime.RegisterNSLoader("yamlscript/common", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlscript.common"
func LoadNS() {
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym_N := lang.NewSymbolUnchecked("N")
	sym_R := lang.NewSymbolUnchecked("R")
	sym_S := lang.NewSymbolUnchecked("S")
	sym_atom_QMARK_ := lang.NewSymbolUnchecked("atom?")
	sym_chop := lang.NewSymbolUnchecked("chop")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_drop_DASH_last := lang.NewSymbolUnchecked("drop-last")
	sym_join := lang.NewSymbolUnchecked("join")
	sym_re_DASH_find := lang.NewSymbolUnchecked("re-find")
	sym_re_DASH_find_PLUS_ := lang.NewSymbolUnchecked("re-find+")
	sym_regex_QMARK_ := lang.NewSymbolUnchecked("regex?")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	sym_type := lang.NewSymbolUnchecked("type")
	sym_util := lang.NewSymbolUnchecked("util")
	sym_x := lang.NewSymbolUnchecked("x")
	sym_yamlscript_DOT_common := lang.NewSymbolUnchecked("yamlscript.common")
	sym_yamlscript_DOT_util := lang.NewSymbolUnchecked("yamlscript.util")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/drop-last
	var_clojure_DOT_core_drop_DASH_last := lang.InternVarName(sym_clojure_DOT_core, sym_drop_DASH_last)
	// var clojure.core/re-find
	var_clojure_DOT_core_re_DASH_find := lang.InternVarName(sym_clojure_DOT_core, sym_re_DASH_find)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var clojure.core/type
	var_clojure_DOT_core_type := lang.InternVarName(sym_clojure_DOT_core, sym_type)
	// var clojure.string/join
	var_clojure_DOT_string_join := lang.InternVarName(sym_clojure_DOT_string, sym_join)
	// var yamlscript.common/atom?
	var_yamlscript_DOT_common_atom_QMARK_ := lang.InternVarName(sym_yamlscript_DOT_common, sym_atom_QMARK_)
	// var yamlscript.common/chop
	var_yamlscript_DOT_common_chop := lang.InternVarName(sym_yamlscript_DOT_common, sym_chop)
	// var yamlscript.common/re-find+
	var_yamlscript_DOT_common_re_DASH_find_PLUS_ := lang.InternVarName(sym_yamlscript_DOT_common, sym_re_DASH_find_PLUS_)
	// var yamlscript.common/regex?
	var_yamlscript_DOT_common_regex_QMARK_ := lang.InternVarName(sym_yamlscript_DOT_common, sym_regex_QMARK_)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlscript_DOT_common)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"cond-lets",
			"condf",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"die",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"eprint",
			"eprintln",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"if-lets",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
			"when-lets",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	ns.AddAlias(sym_util, lang.FindOrCreateNamespace(sym_yamlscript_DOT_util))
	// atom?
	{
		tmp0 := sym_atom_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := checkDerefVar(var_clojure_DOT_core__EQ_)
			tmp4 := checkDerefVar(var_clojure_DOT_core_type)
			tmp5 := lang.Apply1(tmp4, v2)
			tmp6 := lang.Apply2(tmp3, tmp5, nil)
			return tmp6
		})
		aotDirectFn0 = tmp1
		var_yamlscript_DOT_common_atom_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion0 = var_yamlscript_DOT_common_atom_QMARK_.RootVersion()
		var_yamlscript_DOT_common_atom_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlscript/common.glj", kw_line, int(29), kw_column, int(7), kw_end_DASH_line, int(29), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yamlscript_DOT_common))
		})
	}
	// chop
	{
		tmp0 := sym_chop
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			lang.FnFunc1(func(p0 any) any {
				v2 := p0
				_ = v2
				tmp3 := checkDerefVar(var_yamlscript_DOT_common_chop)
				tmp4 := lang.Apply2(tmp3, int64(1), v2)
				return tmp4
			}),
			lang.FnFunc2(func(p0, p1 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				var tmp4 any
				{ // let
					// let binding "lst"
					tmp5 := checkDerefVar(var_clojure_DOT_core_drop_DASH_last)
					tmp6 := lang.Apply2(tmp5, v2, v3)
					var v7 any = tmp6
					_ = v7
					var tmp8 any
					tmp9 := checkDerefVar(var_clojure_DOT_core_string_QMARK_)
					tmp10 := lang.Apply1(tmp9, v3)
					if lang.IsTruthy(tmp10) {
						tmp11 := checkDerefVar(var_clojure_DOT_string_join)
						tmp12 := lang.Apply2(tmp11, "", v7)
						tmp8 = tmp12
					} else {
						tmp8 = v7
					}
					tmp4 = tmp8
				} // end let
				return tmp4
			}),
			nil,
			nil,
			nil,
			0,
		)
		var_yamlscript_DOT_common_chop = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlscript_DOT_common_chop.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlscript/common.glj", kw_line, int(32), kw_column, int(7), kw_end_DASH_line, int(32), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_S), lang.NewVector(sym_N, sym_S)), kw_ns, lang.FindOrCreateNamespace(sym_yamlscript_DOT_common))
		})
	}
	// re-find+
	{
		tmp0 := sym_re_DASH_find_PLUS_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := checkDerefVar(var_clojure_DOT_core_re_DASH_find)
			tmp5 := checkDerefVar(var_clojure_DOT_core_str)
			tmp6 := lang.Apply1(tmp5, v3)
			tmp7 := lang.Apply2(tmp4, v2, tmp6)
			return tmp7
		})
		aotDirectFn1 = tmp1
		var_yamlscript_DOT_common_re_DASH_find_PLUS_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion1 = var_yamlscript_DOT_common_re_DASH_find_PLUS_.RootVersion()
		var_yamlscript_DOT_common_re_DASH_find_PLUS_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlscript/common.glj", kw_line, int(80), kw_column, int(7), kw_end_DASH_line, int(80), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym_R, sym_S)), kw_ns, lang.FindOrCreateNamespace(sym_yamlscript_DOT_common))
		})
	}
	// regex?
	{
		tmp0 := sym_regex_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := checkDerefVar(var_clojure_DOT_core__EQ_)
			tmp4 := checkDerefVar(var_clojure_DOT_core_type)
			tmp5 := lang.Apply1(tmp4, v2)
			tmp6 := reflect.TypeOf((*regexp4.Regexp)(nil))
			tmp7 := lang.Apply2(tmp3, tmp5, tmp6)
			return tmp7
		})
		aotDirectFn2 = tmp1
		var_yamlscript_DOT_common_regex_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion2 = var_yamlscript_DOT_common_regex_QMARK_.RootVersion()
		var_yamlscript_DOT_common_regex_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlscript/common.glj", kw_line, int(83), kw_column, int(7), kw_end_DASH_line, int(83), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yamlscript_DOT_common))
		})
	}
}
