// Code generated by glojure codegen. DO NOT EDIT.

package ipc

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	io5 "io"
	exec4 "os/exec"
	reflect "reflect"
)

var aotDirectFn0 lang.FnFunc1
var aotRootVersion0 *lang.VarRootVersion

func init() {
	runtime.RegisterNSLoader("ys/ipc", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "ys.ipc"
func LoadNS() {
	sym__AMP_ := lang.NewSymbolUnchecked("&")
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_args := lang.NewSymbolUnchecked("args")
	sym_b := lang.NewSymbolUnchecked("b")
	sym_bytes_DASH_to_DASH_str := lang.NewSymbolUnchecked("bytes-to-str")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_empty_QMARK_ := lang.NewSymbolUnchecked("empty?")
	sym_first := lang.NewSymbolUnchecked("first")
	sym_join := lang.NewSymbolUnchecked("join")
	sym_next := lang.NewSymbolUnchecked("next")
	sym_not := lang.NewSymbolUnchecked("not")
	sym_nth := lang.NewSymbolUnchecked("nth")
	sym_process := lang.NewSymbolUnchecked("process")
	sym_seq := lang.NewSymbolUnchecked("seq")
	sym_sh := lang.NewSymbolUnchecked("sh")
	sym_shell := lang.NewSymbolUnchecked("shell")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_vec := lang.NewSymbolUnchecked("vec")
	sym_ys_DOT_ipc := lang.NewSymbolUnchecked("ys.ipc")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_err := lang.NewKeyword("err")
	kw_exit := lang.NewKeyword("exit")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_out := lang.NewKeyword("out")
	kw_private := lang.NewKeyword("private")
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/empty?
	var_clojure_DOT_core_empty_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_empty_QMARK_)
	// var clojure.core/first
	var_clojure_DOT_core_first := lang.InternVarName(sym_clojure_DOT_core, sym_first)
	// var clojure.core/next
	var_clojure_DOT_core_next := lang.InternVarName(sym_clojure_DOT_core, sym_next)
	// var clojure.core/not
	var_clojure_DOT_core_not := lang.InternVarName(sym_clojure_DOT_core, sym_not)
	// var clojure.core/nth
	var_clojure_DOT_core_nth := lang.InternVarName(sym_clojure_DOT_core, sym_nth)
	// var clojure.core/seq
	var_clojure_DOT_core_seq := lang.InternVarName(sym_clojure_DOT_core, sym_seq)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/vec
	var_clojure_DOT_core_vec := lang.InternVarName(sym_clojure_DOT_core, sym_vec)
	// var clojure.string/join
	var_clojure_DOT_string_join := lang.InternVarName(sym_clojure_DOT_string, sym_join)
	// var ys.ipc/bytes-to-str
	var_ys_DOT_ipc_bytes_DASH_to_DASH_str := lang.InternVarName(sym_ys_DOT_ipc, sym_bytes_DASH_to_DASH_str)
	// var ys.ipc/process
	var_ys_DOT_ipc_process := lang.InternVarName(sym_ys_DOT_ipc, sym_process)
	// var ys.ipc/sh
	var_ys_DOT_ipc_sh := lang.InternVarName(sym_ys_DOT_ipc, sym_sh)
	// var ys.ipc/shell
	var_ys_DOT_ipc_shell := lang.InternVarName(sym_ys_DOT_ipc, sym_shell)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_ys_DOT_ipc)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	// bytes-to-str
	{
		tmp0 := sym_bytes_DASH_to_DASH_str
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Convert Go []byte to string"
			tmp3 := lang.Apply2(fmt.Sprintf, "%s", v2)
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_ys_DOT_ipc_bytes_DASH_to_DASH_str = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion0 = var_ys_DOT_ipc_bytes_DASH_to_DASH_str.RootVersion()
		var_ys_DOT_ipc_bytes_DASH_to_DASH_str.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(14), kw_column, int(8), kw_end_DASH_line, int(14), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_b)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
	// process
	{
		tmp0 := sym_process
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				_ = "Execute command via /bin/sh -c (joins args into single command string)"
				tmp3 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp4 := checkDerefVar(var_ys_DOT_ipc_shell)
				tmp5 := lang.Apply2(tmp3, tmp4, v2)
				return tmp5
			}),
			0,
		)
		var_ys_DOT_ipc_process = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_ipc_process.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(54), kw_column, int(7), kw_end_DASH_line, int(54), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
	// sh
	{
		tmp0 := sym_sh
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				_ = "Execute command directly (first arg is command, rest are arguments)"
				var tmp3 any
				tmp4 := checkDerefVar(var_clojure_DOT_core_empty_QMARK_)
				tmp5 := lang.Apply1(tmp4, v2)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.NewMap(kw_exit, int64(1), kw_out, "", kw_err, "No command specified")
					tmp7 := lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(25), kw_column, int(5), kw_end_DASH_line, int(25), kw_end_DASH_column, int(49))
					tmp8, err := lang.WithMeta(tmp6, tmp7.(lang.IPersistentMap))
					if err != nil {
						panic(err)
					}
					tmp3 = tmp8
				} else {
					var tmp9 any
					{ // let
						// let binding "vec__1"
						var v10 any = v2
						_ = v10
						// let binding "seq__2"
						tmp11 := checkDerefVar(var_clojure_DOT_core_seq)
						tmp12 := lang.Apply1(tmp11, v10)
						var v13 any = tmp12
						_ = v13
						// let binding "first__3"
						tmp14 := checkDerefVar(var_clojure_DOT_core_first)
						tmp15 := lang.Apply1(tmp14, v13)
						var v16 any = tmp15
						_ = v16
						// let binding "seq__2"
						tmp17 := checkDerefVar(var_clojure_DOT_core_next)
						tmp18 := lang.Apply1(tmp17, v13)
						var v19 any = tmp18
						_ = v19
						// let binding "cmd-name"
						var v20 any = v16
						_ = v20
						// let binding "cmd-args"
						var v21 any = v19
						_ = v21
						// let binding "cmd"
						tmp22 := checkDerefVar(var_clojure_DOT_core_apply)
						tmp23 := checkDerefVar(var_clojure_DOT_core_vec)
						tmp24 := lang.Apply1(tmp23, v21)
						tmp25 := lang.Apply3(tmp22, exec4.Command, v20, tmp24)
						var v26 any = tmp25
						_ = v26
						// let binding "vec__4"
						tmp27, ok := lang.FieldOrMethod(v26, "StdoutPipe")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v26, "StdoutPipe")))
						}
						var tmp28 any
						switch reflect.TypeOf(tmp27).Kind() {
						case reflect.Func:
							tmp28 = lang.Apply(tmp27, nil)
						default:
							tmp28 = tmp27
						}
						var v29 any = tmp28
						_ = v29
						// let binding "stdout-pipe"
						tmp30 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp31 := lang.Apply3(tmp30, v29, int64(0), nil)
						var v32 any = tmp31
						_ = v32
						// let binding "stdout-err"
						tmp33 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp34 := lang.Apply3(tmp33, v29, int64(1), nil)
						var v35 any = tmp34
						_ = v35
						// let binding "vec__7"
						tmp36, ok := lang.FieldOrMethod(v26, "StderrPipe")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v26, "StderrPipe")))
						}
						var tmp37 any
						switch reflect.TypeOf(tmp36).Kind() {
						case reflect.Func:
							tmp37 = lang.Apply(tmp36, nil)
						default:
							tmp37 = tmp36
						}
						var v38 any = tmp37
						_ = v38
						// let binding "stderr-pipe"
						tmp39 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp40 := lang.Apply3(tmp39, v38, int64(0), nil)
						var v41 any = tmp40
						_ = v41
						// let binding "stderr-err"
						tmp42 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp43 := lang.Apply3(tmp42, v38, int64(1), nil)
						var v44 any = tmp43
						_ = v44
						var tmp45 any
						var tmp46 any
						{ // let
							// let binding "or__0__auto__"
							tmp47 := checkDerefVar(var_clojure_DOT_core_not)
							tmp48 := lang.Identical(v35, nil)
							tmp49 := lang.Apply1(tmp47, tmp48)
							var v50 any = tmp49
							_ = v50
							var tmp51 any
							if lang.IsTruthy(v50) {
								tmp51 = v50
							} else {
								tmp52 := checkDerefVar(var_clojure_DOT_core_not)
								tmp53 := lang.Identical(v44, nil)
								tmp54 := lang.Apply1(tmp52, tmp53)
								tmp51 = tmp54
							}
							tmp46 = tmp51
						} // end let
						if lang.IsTruthy(tmp46) {
							tmp47 := checkDerefVar(var_clojure_DOT_core_str)
							tmp48 := lang.Apply1(tmp47, "Failed to create pipes")
							tmp49 := lang.NewMap(kw_exit, int64(1), kw_out, "", kw_err, tmp48)
							tmp50 := lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(31), kw_column, int(9), kw_end_DASH_line, int(31), kw_end_DASH_column, int(61))
							tmp51, err := lang.WithMeta(tmp49, tmp50.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp45 = tmp51
						} else {
							var tmp52 any
							{ // let
								// let binding "start-err"
								tmp53, ok := lang.FieldOrMethod(v26, "Start")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v26, "Start")))
								}
								var tmp54 any
								switch reflect.TypeOf(tmp53).Kind() {
								case reflect.Func:
									tmp54 = lang.Apply(tmp53, nil)
								default:
									tmp54 = tmp53
								}
								var v55 any = tmp54
								_ = v55
								var tmp56 any
								tmp57 := checkDerefVar(var_clojure_DOT_core_not)
								tmp58 := lang.Identical(v55, nil)
								tmp59 := lang.Apply1(tmp57, tmp58)
								if lang.IsTruthy(tmp59) {
									tmp60 := checkDerefVar(var_clojure_DOT_core_str)
									tmp61 := lang.Apply2(tmp60, "Failed to start: ", v55)
									tmp62 := lang.NewMap(kw_exit, int64(1), kw_out, "", kw_err, tmp61)
									tmp63 := lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(34), kw_column, int(13), kw_end_DASH_line, int(34), kw_end_DASH_column, int(70))
									tmp64, err := lang.WithMeta(tmp62, tmp63.(lang.IPersistentMap))
									if err != nil {
										panic(err)
									}
									tmp56 = tmp64
								} else {
									var tmp65 any
									{ // let
										// let binding "vec__10"
										tmp66 := lang.Apply1(io5.ReadAll, v32)
										var v67 any = tmp66
										_ = v67
										// let binding "stdout-bytes"
										tmp68 := checkDerefVar(var_clojure_DOT_core_nth)
										tmp69 := lang.Apply3(tmp68, v67, int64(0), nil)
										var v70 any = tmp69
										_ = v70
										// let binding "stdout-read-err"
										tmp71 := checkDerefVar(var_clojure_DOT_core_nth)
										tmp72 := lang.Apply3(tmp71, v67, int64(1), nil)
										var v73 any = tmp72
										_ = v73
										// let binding "vec__13"
										tmp74 := lang.Apply1(io5.ReadAll, v41)
										var v75 any = tmp74
										_ = v75
										// let binding "stderr-bytes"
										tmp76 := checkDerefVar(var_clojure_DOT_core_nth)
										tmp77 := lang.Apply3(tmp76, v75, int64(0), nil)
										var v78 any = tmp77
										_ = v78
										// let binding "stderr-read-err"
										tmp79 := checkDerefVar(var_clojure_DOT_core_nth)
										tmp80 := lang.Apply3(tmp79, v75, int64(1), nil)
										var v81 any = tmp80
										_ = v81
										// let binding "wait-err"
										tmp82, ok := lang.FieldOrMethod(v26, "Wait")
										if !ok {
											panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v26, "Wait")))
										}
										var tmp83 any
										switch reflect.TypeOf(tmp82).Kind() {
										case reflect.Func:
											tmp83 = lang.Apply(tmp82, nil)
										default:
											tmp83 = tmp82
										}
										var v84 any = tmp83
										_ = v84
										// let binding "exit-code"
										var tmp85 any
										tmp86 := lang.Identical(v84, nil)
										if lang.IsTruthy(tmp86) {
											tmp85 = int64(0)
										} else {
											tmp87, ok := lang.FieldOrMethod(v26, "ProcessState")
											if !ok {
												panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v26, "ProcessState")))
											}
											var tmp88 any
											switch reflect.TypeOf(tmp87).Kind() {
											case reflect.Func:
												tmp88 = lang.Apply(tmp87, nil)
											default:
												tmp88 = tmp87
											}
											tmp89, ok := lang.FieldOrMethod(tmp88, "ExitCode")
											if !ok {
												panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp88, "ExitCode")))
											}
											var tmp90 any
											switch reflect.TypeOf(tmp89).Kind() {
											case reflect.Func:
												tmp90 = lang.Apply(tmp89, nil)
											default:
												tmp90 = tmp89
											}
											tmp85 = tmp90
										}
										var v91 any = tmp85
										_ = v91
										var tmp92 any
										tmp93 := lang.Identical(v73, nil)
										if lang.IsTruthy(tmp93) {
											tmp94 := var_ys_DOT_ipc_bytes_DASH_to_DASH_str.RootVersion() == aotRootVersion0 && !var_ys_DOT_ipc_bytes_DASH_to_DASH_str.IsMacro()
											var tmp95 any
											if !tmp94 {
												tmp95 = checkDerefVar(var_ys_DOT_ipc_bytes_DASH_to_DASH_str)
											}
											var tmp96 any
											if tmp94 {
												tmp96 = aotDirectFn0(v70)
											} else {
												tmp96 = lang.Apply1(tmp95, v70)
											}
											tmp92 = tmp96
										} else {
											tmp92 = ""
										}
										var tmp97 any
										tmp98 := lang.Identical(v81, nil)
										if lang.IsTruthy(tmp98) {
											tmp99 := var_ys_DOT_ipc_bytes_DASH_to_DASH_str.RootVersion() == aotRootVersion0 && !var_ys_DOT_ipc_bytes_DASH_to_DASH_str.IsMacro()
											var tmp100 any
											if !tmp99 {
												tmp100 = checkDerefVar(var_ys_DOT_ipc_bytes_DASH_to_DASH_str)
											}
											var tmp101 any
											if tmp99 {
												tmp101 = aotDirectFn0(v78)
											} else {
												tmp101 = lang.Apply1(tmp100, v78)
											}
											tmp97 = tmp101
										} else {
											tmp97 = ""
										}
										tmp102 := lang.NewMap(kw_exit, v91, kw_out, tmp92, kw_err, tmp97)
										tmp103 := lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(41), kw_column, int(15), kw_end_DASH_line, int(47), kw_end_DASH_column, int(26))
										tmp104, err := lang.WithMeta(tmp102, tmp103.(lang.IPersistentMap))
										if err != nil {
											panic(err)
										}
										tmp65 = tmp104
									} // end let
									tmp56 = tmp65
								}
								tmp52 = tmp56
							} // end let
							tmp45 = tmp52
						}
						tmp9 = tmp45
					} // end let
					tmp3 = tmp9
				}
				return tmp3
			}),
			0,
		)
		var_ys_DOT_ipc_sh = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_ipc_sh.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(22), kw_column, int(7), kw_end_DASH_line, int(22), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
	// shell
	{
		tmp0 := sym_shell
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				_ = "Execute command via /bin/sh -c (joins args into single command string)"
				var tmp3 any
				{ // let
					// let binding "cmd-str"
					tmp4 := checkDerefVar(var_clojure_DOT_string_join)
					tmp5 := lang.Apply2(tmp4, " ", v2)
					var v6 any = tmp5
					_ = v6
					tmp7 := checkDerefVar(var_ys_DOT_ipc_sh)
					tmp8 := lang.Apply3(tmp7, "/bin/sh", "-c", v6)
					tmp3 = tmp8
				} // end let
				return tmp3
			}),
			0,
		)
		var_ys_DOT_ipc_shell = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_ipc_shell.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(49), kw_column, int(7), kw_end_DASH_line, int(49), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
}
