FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    perl \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*
