// Code generated by glojure codegen. DO NOT EDIT.

package http

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	io5 "io"
	http4 "net/http"
	reflect "reflect"
	strings6 "strings"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.ArityFn
var aotDirectFn1Arity1 lang.FnFunc1
var aotDirectFn1Arity2 lang.FnFunc2
var aotDirectFn2 lang.FnFunc2

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("ys/http", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "ys.http"
func LoadNS() {
	sym_b := lang.NewSymbolUnchecked("b")
	sym_bytes_DASH_to_DASH_str := lang.NewSymbolUnchecked("bytes-to-str")
	sym_chunk_DASH_first := lang.NewSymbolUnchecked("chunk-first")
	sym_chunk_DASH_rest := lang.NewSymbolUnchecked("chunk-rest")
	sym_chunked_DASH_seq_QMARK_ := lang.NewSymbolUnchecked("chunked-seq?")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_get := lang.NewSymbolUnchecked("get")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_not := lang.NewSymbolUnchecked("not")
	sym_opts := lang.NewSymbolUnchecked("opts")
	sym_post := lang.NewSymbolUnchecked("post")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_url := lang.NewSymbolUnchecked("url")
	sym_ys_DOT_http := lang.NewSymbolUnchecked("ys.http")
	kw_arglists := lang.NewKeyword("arglists")
	kw_body := lang.NewKeyword("body")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_headers := lang.NewKeyword("headers")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	kw_status := lang.NewKeyword("status")
	// var clojure.core/chunk-first
	var_clojure_DOT_core_chunk_DASH_first := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_first)
	// var clojure.core/chunk-rest
	var_clojure_DOT_core_chunk_DASH_rest := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_rest)
	// var clojure.core/chunked-seq?
	var_clojure_DOT_core_chunked_DASH_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_chunked_DASH_seq_QMARK_)
	// var clojure.core/name
	var_clojure_DOT_core_name := lang.InternVarName(sym_clojure_DOT_core, sym_name)
	// var clojure.core/not
	var_clojure_DOT_core_not := lang.InternVarName(sym_clojure_DOT_core, sym_not)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var ys.http/bytes-to-str
	var_ys_DOT_http_bytes_DASH_to_DASH_str := lang.InternVarName(sym_ys_DOT_http, sym_bytes_DASH_to_DASH_str)
	// var ys.http/get
	var_ys_DOT_http_get := lang.InternVarName(sym_ys_DOT_http, sym_get)
	// var ys.http/post
	var_ys_DOT_http_post := lang.InternVarName(sym_ys_DOT_http, sym_post)
	aotExternalFn1 := aotLinkFn1(var_clojure_DOT_core_not)
	aotExternalFn11 := aotLinkFn1(var_clojure_DOT_core_name)
	aotExternalFn2 := aotLinkFn2(var_clojure_DOT_core_str)
	aotExternalFn4 := aotLinkFn1(var_clojure_DOT_core_str)
	aotExternalFn5 := aotLinkFn1(var_clojure_DOT_core_chunked_DASH_seq_QMARK_)
	aotExternalFn6 := aotLinkFn1(var_clojure_DOT_core_chunk_DASH_first)
	aotExternalFn7 := aotLinkFn1(var_clojure_DOT_core_chunk_DASH_rest)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_ys_DOT_http)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"get",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	// bytes-to-str
	{
		tmp0 := sym_bytes_DASH_to_DASH_str
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Convert Go []byte to string"
			tmp3 := lang.Apply2(fmt.Sprintf, "%s", v2)
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_ys_DOT_http_bytes_DASH_to_DASH_str = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_http_bytes_DASH_to_DASH_str.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/http.glj", kw_line, int(15), kw_column, int(8), kw_end_DASH_line, int(15), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_b)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_http))
		})
	}
	// get
	{
		tmp0 := sym_get
		var tmp1 lang.ArityFn
		aotDirectFn1Arity1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewMap()
			tmp4 := aotDirectFn1Arity2(v2, tmp3)
			return tmp4
		})
		aotDirectFn1Arity2 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "vec__20"
				tmp5 := lang.Apply3(http4.NewRequest, "GET", v2, nil)
				var v6 any = tmp5
				_ = v6
				// let binding "req"
				tmp7 := runtime.RT.NthDefault(v6, lang.IntCast(int64(0)), nil)
				var v8 any = tmp7
				_ = v8
				// let binding "req-err"
				tmp9 := runtime.RT.NthDefault(v6, lang.IntCast(int64(1)), nil)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				tmp12 := lang.Identical(v10, nil)
				tmp13 := aotExternalFn1(tmp12)
				if lang.IsTruthy(tmp13) {
					tmp14 := aotExternalFn2("Failed to create request: ", v10)
					tmp15 := lang.NewMap(kw_status, int64(500), kw_body, tmp14)
					tmp11 = tmp15
				} else {
					var tmp16 any
					{ // let
						// let binding "seq_23"
						tmp17 := kw_headers.Invoke1(v3)
						tmp18 := lang.Seq(tmp17)
						var v19 any = tmp18
						_ = v19
						// let binding "chunk_24"
						var v20 any = nil
						_ = v20
						// let binding "count_25"
						var v21 any = int64(0)
						_ = v21
						// let binding "i_26"
						var v22 any = int64(0)
						_ = v22
						for {
							var tmp23 any
							tmp24 := lang.Numbers.Lt(v22, v21)
							if lang.IsTruthy(tmp24) {
								var tmp25 any
								{ // let
									// let binding "vec__27"
									tmp26 := v20.(interface{ Nth(int) any }).Nth(lang.IntCast(v22))
									var v27 any = tmp26
									_ = v27
									// let binding "k"
									tmp28 := runtime.RT.NthDefault(v27, lang.IntCast(int64(0)), nil)
									var v29 any = tmp28
									_ = v29
									// let binding "v"
									tmp30 := runtime.RT.NthDefault(v27, lang.IntCast(int64(1)), nil)
									var v31 any = tmp30
									_ = v31
									tmp32, ok := lang.FieldOrMethod(v8, "Header")
									if !ok {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Header")))
									}
									var tmp33 any
									switch reflect.TypeOf(tmp32).Kind() {
									case reflect.Func:
										tmp33 = lang.Apply(tmp32, nil)
									default:
										tmp33 = tmp32
									}
									tmp34 := aotExternalFn4(v29)
									tmp35 := aotExternalFn4(v31)
									tmp36, _ := lang.FieldOrMethod(tmp33, "Set")
									if reflect.TypeOf(tmp36).Kind() != reflect.Func {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("Set is not a function")))
									}
									tmp37 := lang.Apply2(tmp36, tmp34, tmp35)
									_ = tmp37
									var tmp38 any = v19
									var tmp39 any = v20
									var tmp40 any = v21
									tmp42 := lang.Numbers.Unchecked_inc(v22)
									var tmp41 any = tmp42
									v19 = tmp38
									v20 = tmp39
									v21 = tmp40
									v22 = tmp41
									continue
								} // end let
								tmp23 = tmp25
							} else {
								var tmp26 any
								{ // let
									// let binding "temp__0__auto__"
									tmp27 := lang.Seq(v19)
									var v28 any = tmp27
									_ = v28
									var tmp29 any
									if lang.IsTruthy(v28) {
										var tmp30 any
										{ // let
											// let binding "seq_23"
											var v31 any = v28
											_ = v31
											var tmp32 any
											tmp33 := aotExternalFn5(v31)
											if lang.IsTruthy(tmp33) {
												var tmp34 any
												{ // let
													// let binding "c__0__auto__"
													tmp35 := aotExternalFn6(v31)
													var v36 any = tmp35
													_ = v36
													tmp38 := aotExternalFn7(v31)
													var tmp37 any = tmp38
													var tmp39 any = v36
													tmp41 := lang.Count(v36)
													tmp42 := runtime.RT.IntCast(tmp41)
													var tmp40 any = tmp42
													tmp44 := runtime.RT.IntCast(int64(0))
													var tmp43 any = tmp44
													v19 = tmp37
													v20 = tmp39
													v21 = tmp40
													v22 = tmp43
													continue
												} // end let
												tmp32 = tmp34
											} else {
												var tmp35 any
												{ // let
													// let binding "vec__30"
													tmp36 := lang.First(v31)
													var v37 any = tmp36
													_ = v37
													// let binding "k"
													tmp38 := runtime.RT.NthDefault(v37, lang.IntCast(int64(0)), nil)
													var v39 any = tmp38
													_ = v39
													// let binding "v"
													tmp40 := runtime.RT.NthDefault(v37, lang.IntCast(int64(1)), nil)
													var v41 any = tmp40
													_ = v41
													tmp42, ok := lang.FieldOrMethod(v8, "Header")
													if !ok {
														panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Header")))
													}
													var tmp43 any
													switch reflect.TypeOf(tmp42).Kind() {
													case reflect.Func:
														tmp43 = lang.Apply(tmp42, nil)
													default:
														tmp43 = tmp42
													}
													tmp44 := aotExternalFn4(v39)
													tmp45 := aotExternalFn4(v41)
													tmp46, _ := lang.FieldOrMethod(tmp43, "Set")
													if reflect.TypeOf(tmp46).Kind() != reflect.Func {
														panic(lang.NewIllegalArgumentError(fmt.Sprintf("Set is not a function")))
													}
													tmp47 := lang.Apply2(tmp46, tmp44, tmp45)
													_ = tmp47
													tmp49 := lang.Next(v31)
													var tmp48 any = tmp49
													var tmp50 any = nil
													var tmp51 any = int64(0)
													var tmp52 any = int64(0)
													v19 = tmp48
													v20 = tmp50
													v21 = tmp51
													v22 = tmp52
													continue
												} // end let
												tmp32 = tmp35
											}
											tmp30 = tmp32
										} // end let
										tmp29 = tmp30
									} else {
									}
									tmp26 = tmp29
								} // end let
								tmp23 = tmp26
							}
							tmp16 = tmp23
							break
						}
					} // end let
					_ = tmp16
					var tmp17 any
					{ // let
						// let binding "client"
						var v18 any = http4.DefaultClient
						_ = v18
						// let binding "vec__33"
						tmp19, _ := lang.FieldOrMethod(v18, "Do")
						if reflect.TypeOf(tmp19).Kind() != reflect.Func {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("Do is not a function")))
						}
						tmp20 := lang.Apply1(tmp19, v8)
						var v21 any = tmp20
						_ = v21
						// let binding "resp"
						tmp22 := runtime.RT.NthDefault(v21, lang.IntCast(int64(0)), nil)
						var v23 any = tmp22
						_ = v23
						// let binding "resp-err"
						tmp24 := runtime.RT.NthDefault(v21, lang.IntCast(int64(1)), nil)
						var v25 any = tmp24
						_ = v25
						var tmp26 any
						tmp27 := lang.Identical(v25, nil)
						tmp28 := aotExternalFn1(tmp27)
						if lang.IsTruthy(tmp28) {
							tmp29 := aotExternalFn2("Request failed: ", v25)
							tmp30 := lang.NewMap(kw_status, int64(500), kw_body, tmp29)
							tmp26 = tmp30
						} else {
							var tmp31 any
							{ // let
								// let binding "vec__36"
								tmp32, ok := lang.FieldOrMethod(v23, "Body")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v23, "Body")))
								}
								var tmp33 any
								switch reflect.TypeOf(tmp32).Kind() {
								case reflect.Func:
									tmp33 = lang.Apply(tmp32, nil)
								default:
									tmp33 = tmp32
								}
								tmp34 := lang.Apply1(io5.ReadAll, tmp33)
								var v35 any = tmp34
								_ = v35
								// let binding "body-bytes"
								tmp36 := runtime.RT.NthDefault(v35, lang.IntCast(int64(0)), nil)
								var v37 any = tmp36
								_ = v37
								// let binding "body-err"
								tmp38 := runtime.RT.NthDefault(v35, lang.IntCast(int64(1)), nil)
								var v39 any = tmp38
								_ = v39
								tmp40, ok := lang.FieldOrMethod(v23, "Body")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v23, "Body")))
								}
								var tmp41 any
								switch reflect.TypeOf(tmp40).Kind() {
								case reflect.Func:
									tmp41 = lang.Apply(tmp40, nil)
								default:
									tmp41 = tmp40
								}
								tmp42, ok := lang.FieldOrMethod(tmp41, "Close")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp41, "Close")))
								}
								var tmp43 any
								switch reflect.TypeOf(tmp42).Kind() {
								case reflect.Func:
									tmp43 = lang.Apply(tmp42, nil)
								default:
									tmp43 = tmp42
								}
								_ = tmp43
								tmp44, ok := lang.FieldOrMethod(v23, "StatusCode")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v23, "StatusCode")))
								}
								var tmp45 any
								switch reflect.TypeOf(tmp44).Kind() {
								case reflect.Func:
									tmp45 = lang.Apply(tmp44, nil)
								default:
									tmp45 = tmp44
								}
								var tmp46 any
								tmp47 := lang.Identical(v39, nil)
								if lang.IsTruthy(tmp47) {
									tmp48 := aotDirectFn0(v37)
									tmp46 = tmp48
								} else {
									tmp49, ok := lang.FieldOrMethod(v39, "Error")
									if !ok {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v39, "Error")))
									}
									var tmp50 any
									switch reflect.TypeOf(tmp49).Kind() {
									case reflect.Func:
										tmp50 = lang.Apply(tmp49, nil)
									default:
										tmp50 = tmp49
									}
									tmp51 := aotExternalFn2("Failed to read response: ", tmp50)
									tmp46 = tmp51
								}
								tmp52 := lang.NewMap(kw_status, tmp45, kw_body, tmp46)
								tmp31 = tmp52
							} // end let
							tmp26 = tmp31
						}
						tmp17 = tmp26
					} // end let
					tmp11 = tmp17
				}
				tmp4 = tmp11
			} // end let
			return tmp4
		})
		tmp1 = lang.NewArityFn(
			nil,
			aotDirectFn1Arity1,
			aotDirectFn1Arity2,
			nil,
			nil,
			nil,
			0,
		)
		aotDirectFn1 = tmp1
		var_ys_DOT_http_get = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_http_get.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/http.glj", kw_line, int(50), kw_column, int(7), kw_end_DASH_line, int(50), kw_end_DASH_column, int(9), kw_arglists, lang.NewList(lang.NewVector(sym_url), lang.NewVector(sym_url, sym_opts)), kw_doc, "HTTP GET request\n   url: string\n   opts (optional): {:headers {\"Key\" \"Value\"}}\n   returns: {:status N :body \"...\"}", kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_http))
		})
	}
	// post
	{
		tmp0 := sym_post
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "body-str"
				var tmp5 any
				{ // let
					// let binding "or__0__auto__"
					tmp6 := kw_body.Invoke1(v3)
					var v7 any = tmp6
					_ = v7
					var tmp8 any
					if lang.IsTruthy(v7) {
						tmp8 = v7
					} else {
						tmp8 = ""
					}
					tmp5 = tmp8
				} // end let
				var v6 any = tmp5
				_ = v6
				// let binding "reader"
				tmp7 := lang.Apply1(strings6.NewReader, v6)
				var v8 any = tmp7
				_ = v8
				// let binding "vec__1"
				tmp9 := lang.Apply3(http4.NewRequest, "POST", v2, v8)
				var v10 any = tmp9
				_ = v10
				// let binding "req"
				tmp11 := runtime.RT.NthDefault(v10, lang.IntCast(int64(0)), nil)
				var v12 any = tmp11
				_ = v12
				// let binding "req-err"
				tmp13 := runtime.RT.NthDefault(v10, lang.IntCast(int64(1)), nil)
				var v14 any = tmp13
				_ = v14
				var tmp15 any
				tmp16 := lang.Identical(v14, nil)
				tmp17 := aotExternalFn1(tmp16)
				if lang.IsTruthy(tmp17) {
					tmp18, ok := lang.FieldOrMethod(v14, "Error")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v14, "Error")))
					}
					var tmp19 any
					switch reflect.TypeOf(tmp18).Kind() {
					case reflect.Func:
						tmp19 = lang.Apply(tmp18, nil)
					default:
						tmp19 = tmp18
					}
					tmp20 := aotExternalFn2("Failed to create request: ", tmp19)
					tmp21 := lang.NewMap(kw_status, int64(500), kw_body, tmp20)
					tmp15 = tmp21
				} else {
					var tmp22 any
					{ // let
						// let binding "seq_4"
						tmp23 := kw_headers.Invoke1(v3)
						tmp24 := lang.Seq(tmp23)
						var v25 any = tmp24
						_ = v25
						// let binding "chunk_5"
						var v26 any = nil
						_ = v26
						// let binding "count_6"
						var v27 any = int64(0)
						_ = v27
						// let binding "i_7"
						var v28 any = int64(0)
						_ = v28
						for {
							var tmp29 any
							tmp30 := lang.Numbers.Lt(v28, v27)
							if lang.IsTruthy(tmp30) {
								var tmp31 any
								{ // let
									// let binding "vec__8"
									tmp32 := v26.(interface{ Nth(int) any }).Nth(lang.IntCast(v28))
									var v33 any = tmp32
									_ = v33
									// let binding "k"
									tmp34 := runtime.RT.NthDefault(v33, lang.IntCast(int64(0)), nil)
									var v35 any = tmp34
									_ = v35
									// let binding "v"
									tmp36 := runtime.RT.NthDefault(v33, lang.IntCast(int64(1)), nil)
									var v37 any = tmp36
									_ = v37
									tmp38, ok := lang.FieldOrMethod(v12, "Header")
									if !ok {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v12, "Header")))
									}
									var tmp39 any
									switch reflect.TypeOf(tmp38).Kind() {
									case reflect.Func:
										tmp39 = lang.Apply(tmp38, nil)
									default:
										tmp39 = tmp38
									}
									tmp40 := aotExternalFn11(v35)
									tmp41 := aotExternalFn4(v37)
									tmp42, _ := lang.FieldOrMethod(tmp39, "Set")
									if reflect.TypeOf(tmp42).Kind() != reflect.Func {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("Set is not a function")))
									}
									tmp43 := lang.Apply2(tmp42, tmp40, tmp41)
									_ = tmp43
									var tmp44 any = v25
									var tmp45 any = v26
									var tmp46 any = v27
									tmp48 := lang.Numbers.Unchecked_inc(v28)
									var tmp47 any = tmp48
									v25 = tmp44
									v26 = tmp45
									v27 = tmp46
									v28 = tmp47
									continue
								} // end let
								tmp29 = tmp31
							} else {
								var tmp32 any
								{ // let
									// let binding "temp__0__auto__"
									tmp33 := lang.Seq(v25)
									var v34 any = tmp33
									_ = v34
									var tmp35 any
									if lang.IsTruthy(v34) {
										var tmp36 any
										{ // let
											// let binding "seq_4"
											var v37 any = v34
											_ = v37
											var tmp38 any
											tmp39 := aotExternalFn5(v37)
											if lang.IsTruthy(tmp39) {
												var tmp40 any
												{ // let
													// let binding "c__0__auto__"
													tmp41 := aotExternalFn6(v37)
													var v42 any = tmp41
													_ = v42
													tmp44 := aotExternalFn7(v37)
													var tmp43 any = tmp44
													var tmp45 any = v42
													tmp47 := lang.Count(v42)
													tmp48 := runtime.RT.IntCast(tmp47)
													var tmp46 any = tmp48
													tmp50 := runtime.RT.IntCast(int64(0))
													var tmp49 any = tmp50
													v25 = tmp43
													v26 = tmp45
													v27 = tmp46
													v28 = tmp49
													continue
												} // end let
												tmp38 = tmp40
											} else {
												var tmp41 any
												{ // let
													// let binding "vec__11"
													tmp42 := lang.First(v37)
													var v43 any = tmp42
													_ = v43
													// let binding "k"
													tmp44 := runtime.RT.NthDefault(v43, lang.IntCast(int64(0)), nil)
													var v45 any = tmp44
													_ = v45
													// let binding "v"
													tmp46 := runtime.RT.NthDefault(v43, lang.IntCast(int64(1)), nil)
													var v47 any = tmp46
													_ = v47
													tmp48, ok := lang.FieldOrMethod(v12, "Header")
													if !ok {
														panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v12, "Header")))
													}
													var tmp49 any
													switch reflect.TypeOf(tmp48).Kind() {
													case reflect.Func:
														tmp49 = lang.Apply(tmp48, nil)
													default:
														tmp49 = tmp48
													}
													tmp50 := aotExternalFn11(v45)
													tmp51 := aotExternalFn4(v47)
													tmp52, _ := lang.FieldOrMethod(tmp49, "Set")
													if reflect.TypeOf(tmp52).Kind() != reflect.Func {
														panic(lang.NewIllegalArgumentError(fmt.Sprintf("Set is not a function")))
													}
													tmp53 := lang.Apply2(tmp52, tmp50, tmp51)
													_ = tmp53
													tmp55 := lang.Next(v37)
													var tmp54 any = tmp55
													var tmp56 any = nil
													var tmp57 any = int64(0)
													var tmp58 any = int64(0)
													v25 = tmp54
													v26 = tmp56
													v27 = tmp57
													v28 = tmp58
													continue
												} // end let
												tmp38 = tmp41
											}
											tmp36 = tmp38
										} // end let
										tmp35 = tmp36
									} else {
									}
									tmp32 = tmp35
								} // end let
								tmp29 = tmp32
							}
							tmp22 = tmp29
							break
						}
					} // end let
					_ = tmp22
					var tmp23 any
					{ // let
						// let binding "client"
						var v24 any = http4.DefaultClient
						_ = v24
						// let binding "vec__14"
						tmp25, _ := lang.FieldOrMethod(v24, "Do")
						if reflect.TypeOf(tmp25).Kind() != reflect.Func {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("Do is not a function")))
						}
						tmp26 := lang.Apply1(tmp25, v12)
						var v27 any = tmp26
						_ = v27
						// let binding "resp"
						tmp28 := runtime.RT.NthDefault(v27, lang.IntCast(int64(0)), nil)
						var v29 any = tmp28
						_ = v29
						// let binding "resp-err"
						tmp30 := runtime.RT.NthDefault(v27, lang.IntCast(int64(1)), nil)
						var v31 any = tmp30
						_ = v31
						var tmp32 any
						tmp33 := lang.Identical(v31, nil)
						tmp34 := aotExternalFn1(tmp33)
						if lang.IsTruthy(tmp34) {
							tmp35, ok := lang.FieldOrMethod(v31, "Error")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v31, "Error")))
							}
							var tmp36 any
							switch reflect.TypeOf(tmp35).Kind() {
							case reflect.Func:
								tmp36 = lang.Apply(tmp35, nil)
							default:
								tmp36 = tmp35
							}
							tmp37 := aotExternalFn2("Request failed: ", tmp36)
							tmp38 := lang.NewMap(kw_status, int64(500), kw_body, tmp37)
							tmp32 = tmp38
						} else {
							var tmp39 any
							{ // let
								// let binding "vec__17"
								tmp40, ok := lang.FieldOrMethod(v29, "Body")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v29, "Body")))
								}
								var tmp41 any
								switch reflect.TypeOf(tmp40).Kind() {
								case reflect.Func:
									tmp41 = lang.Apply(tmp40, nil)
								default:
									tmp41 = tmp40
								}
								tmp42 := lang.Apply1(io5.ReadAll, tmp41)
								var v43 any = tmp42
								_ = v43
								// let binding "body-bytes"
								tmp44 := runtime.RT.NthDefault(v43, lang.IntCast(int64(0)), nil)
								var v45 any = tmp44
								_ = v45
								// let binding "body-err"
								tmp46 := runtime.RT.NthDefault(v43, lang.IntCast(int64(1)), nil)
								var v47 any = tmp46
								_ = v47
								tmp48, ok := lang.FieldOrMethod(v29, "Body")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v29, "Body")))
								}
								var tmp49 any
								switch reflect.TypeOf(tmp48).Kind() {
								case reflect.Func:
									tmp49 = lang.Apply(tmp48, nil)
								default:
									tmp49 = tmp48
								}
								tmp50, ok := lang.FieldOrMethod(tmp49, "Close")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp49, "Close")))
								}
								var tmp51 any
								switch reflect.TypeOf(tmp50).Kind() {
								case reflect.Func:
									tmp51 = lang.Apply(tmp50, nil)
								default:
									tmp51 = tmp50
								}
								_ = tmp51
								tmp52, ok := lang.FieldOrMethod(v29, "StatusCode")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v29, "StatusCode")))
								}
								var tmp53 any
								switch reflect.TypeOf(tmp52).Kind() {
								case reflect.Func:
									tmp53 = lang.Apply(tmp52, nil)
								default:
									tmp53 = tmp52
								}
								var tmp54 any
								tmp55 := lang.Identical(v47, nil)
								if lang.IsTruthy(tmp55) {
									tmp56 := aotDirectFn0(v45)
									tmp54 = tmp56
								} else {
									tmp57, ok := lang.FieldOrMethod(v47, "Error")
									if !ok {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v47, "Error")))
									}
									var tmp58 any
									switch reflect.TypeOf(tmp57).Kind() {
									case reflect.Func:
										tmp58 = lang.Apply(tmp57, nil)
									default:
										tmp58 = tmp57
									}
									tmp59 := aotExternalFn2("Failed to read response: ", tmp58)
									tmp54 = tmp59
								}
								tmp60 := lang.NewMap(kw_status, tmp53, kw_body, tmp54)
								tmp39 = tmp60
							} // end let
							tmp32 = tmp39
						}
						tmp23 = tmp32
					} // end let
					tmp15 = tmp23
				}
				tmp4 = tmp15
			} // end let
			return tmp4
		})
		aotDirectFn2 = tmp1
		var_ys_DOT_http_post = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_http_post.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/http.glj", kw_line, int(23), kw_column, int(7), kw_end_DASH_line, int(23), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_url, sym_opts)), kw_doc, "HTTP POST request\n   url: string\n   opts: {:headers {\"Key\" \"Value\"} :body \"...\"}\n   returns: {:status N :body \"...\"}", kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_http))
		})
	}
}
