gloat-vars: $(PATH-DEPS)
	@echo '{'
	@echo '  :BB "$(abspath $(BB))"'
	@echo '  :BROTLI "$(abspath $(BROTLI))"'
	@echo '  :GLJ "$(abspath $(GLJ))"'
	@echo '  :GLOJURE-DIR "$(abspath $(GLOJURE-DIR))"'
	@echo '  :GLOJURE-VERSION "$(GLOJURE-VERSION)"'
	@echo '  :GO "$(abspath $(GO))"'
	@echo '  :GRAALVM "$(abspath $(GRAALVM))"'
	@echo '  :GRAAL-CLOJURE-VERSION "$(GRAAL-CLOJURE-VERSION)"'
	@echo '  :JOLT "$(abspath $(JOLT))"'
	@echo '  :LG "$(abspath $(LG))"'
	@echo '  :LEIN "$(abspath $(LEIN))"'
	@echo '  :LET-GO-SRC "$(if $(wildcard $(LET-GO-SRC)),$(abspath $(LET-GO-SRC)),)"'
	@echo '  :LOCAL-HOME "$(abspath $(LOCAL-HOME))"'
	@echo '  :YS "$(abspath $(YS))"'
	@echo '  :YS-V0-GO-DIR "$(abspath $(YS-V0-GO-DIR))"'
	@echo '  :YS-V0-GO-VERSION "$(YS-V0-GO-VERSION)"'
	@echo '}'
