// Code generated by glojure codegen. DO NOT EDIT.

package ipc

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	io5 "io"
	exec4 "os/exec"
	reflect "reflect"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.ArityFn
var aotDirectFn2 lang.ArityFn
var aotDirectFn3 lang.ArityFn

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("ys/ipc", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "ys.ipc"
func LoadNS() {
	sym__AMP_ := lang.NewSymbolUnchecked("&")
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_args := lang.NewSymbolUnchecked("args")
	sym_b := lang.NewSymbolUnchecked("b")
	sym_bytes_DASH_to_DASH_str := lang.NewSymbolUnchecked("bytes-to-str")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_join := lang.NewSymbolUnchecked("join")
	sym_not := lang.NewSymbolUnchecked("not")
	sym_process := lang.NewSymbolUnchecked("process")
	sym_sh := lang.NewSymbolUnchecked("sh")
	sym_shell := lang.NewSymbolUnchecked("shell")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_vec := lang.NewSymbolUnchecked("vec")
	sym_ys_DOT_ipc := lang.NewSymbolUnchecked("ys.ipc")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_err := lang.NewKeyword("err")
	kw_exit := lang.NewKeyword("exit")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_out := lang.NewKeyword("out")
	kw_private := lang.NewKeyword("private")
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/not
	var_clojure_DOT_core_not := lang.InternVarName(sym_clojure_DOT_core, sym_not)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/vec
	var_clojure_DOT_core_vec := lang.InternVarName(sym_clojure_DOT_core, sym_vec)
	// var clojure.string/join
	var_clojure_DOT_string_join := lang.InternVarName(sym_clojure_DOT_string, sym_join)
	// var ys.ipc/bytes-to-str
	var_ys_DOT_ipc_bytes_DASH_to_DASH_str := lang.InternVarName(sym_ys_DOT_ipc, sym_bytes_DASH_to_DASH_str)
	// var ys.ipc/process
	var_ys_DOT_ipc_process := lang.InternVarName(sym_ys_DOT_ipc, sym_process)
	// var ys.ipc/sh
	var_ys_DOT_ipc_sh := lang.InternVarName(sym_ys_DOT_ipc, sym_sh)
	// var ys.ipc/shell
	var_ys_DOT_ipc_shell := lang.InternVarName(sym_ys_DOT_ipc, sym_shell)
	aotExternalFn0 := aotLinkFn2(var_clojure_DOT_core_apply)
	aotExternalFn10 := aotLinkFn2(var_clojure_DOT_core_str)
	aotExternalFn11 := aotLinkFn2(var_clojure_DOT_string_join)
	aotExternalFn5 := aotLinkFn3(var_clojure_DOT_core_apply)
	aotExternalFn6 := aotLinkFn1(var_clojure_DOT_core_vec)
	aotExternalFn8 := aotLinkFn1(var_clojure_DOT_core_not)
	aotExternalFn9 := aotLinkFn1(var_clojure_DOT_core_str)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_ys_DOT_ipc)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	// bytes-to-str
	{
		tmp0 := sym_bytes_DASH_to_DASH_str
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Convert Go []byte to string"
			tmp3 := lang.Apply2(fmt.Sprintf, "%s", v2)
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_ys_DOT_ipc_bytes_DASH_to_DASH_str = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_ipc_bytes_DASH_to_DASH_str.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/ipc.glj", kw_line, int(14), kw_column, int(8), kw_end_DASH_line, int(14), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_b)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
	// sh
	{
		tmp0 := sym_sh
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				_ = "Execute command directly (first arg is command, rest are arguments)"
				var tmp3 any
				tmp4 := lang.IsEmpty(v2)
				if lang.IsTruthy(tmp4) {
					tmp5 := lang.NewMap(kw_exit, int64(1), kw_out, "", kw_err, "No command specified")
					tmp3 = tmp5
				} else {
					var tmp6 any
					{ // let
						// let binding "vec__1"
						var v7 any = v2
						_ = v7
						// let binding "seq__2"
						tmp8 := lang.Seq(v7)
						var v9 any = tmp8
						_ = v9
						// let binding "first__3"
						tmp10 := lang.First(v9)
						var v11 any = tmp10
						_ = v11
						// let binding "seq__2"
						tmp12 := lang.Next(v9)
						var v13 any = tmp12
						_ = v13
						// let binding "cmd-name"
						var v14 any = v11
						_ = v14
						// let binding "cmd-args"
						var v15 any = v13
						_ = v15
						// let binding "cmd"
						tmp16 := aotExternalFn6(v15)
						tmp17 := aotExternalFn5(exec4.Command, v14, tmp16)
						var v18 any = tmp17
						_ = v18
						// let binding "vec__4"
						tmp19, ok := lang.FieldOrMethod(v18, "StdoutPipe")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v18, "StdoutPipe")))
						}
						var tmp20 any
						switch reflect.TypeOf(tmp19).Kind() {
						case reflect.Func:
							tmp20 = lang.Apply(tmp19, nil)
						default:
							tmp20 = tmp19
						}
						var v21 any = tmp20
						_ = v21
						// let binding "stdout-pipe"
						tmp22 := runtime.RT.NthDefault(v21, lang.IntCast(int64(0)), nil)
						var v23 any = tmp22
						_ = v23
						// let binding "stdout-err"
						tmp24 := runtime.RT.NthDefault(v21, lang.IntCast(int64(1)), nil)
						var v25 any = tmp24
						_ = v25
						// let binding "vec__7"
						tmp26, ok := lang.FieldOrMethod(v18, "StderrPipe")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v18, "StderrPipe")))
						}
						var tmp27 any
						switch reflect.TypeOf(tmp26).Kind() {
						case reflect.Func:
							tmp27 = lang.Apply(tmp26, nil)
						default:
							tmp27 = tmp26
						}
						var v28 any = tmp27
						_ = v28
						// let binding "stderr-pipe"
						tmp29 := runtime.RT.NthDefault(v28, lang.IntCast(int64(0)), nil)
						var v30 any = tmp29
						_ = v30
						// let binding "stderr-err"
						tmp31 := runtime.RT.NthDefault(v28, lang.IntCast(int64(1)), nil)
						var v32 any = tmp31
						_ = v32
						var tmp33 any
						var tmp34 any
						{ // let
							// let binding "or__0__auto__"
							tmp35 := lang.Identical(v25, nil)
							tmp36 := aotExternalFn8(tmp35)
							var v37 any = tmp36
							_ = v37
							var tmp38 any
							if lang.IsTruthy(v37) {
								tmp38 = v37
							} else {
								tmp39 := lang.Identical(v32, nil)
								tmp40 := aotExternalFn8(tmp39)
								tmp38 = tmp40
							}
							tmp34 = tmp38
						} // end let
						if lang.IsTruthy(tmp34) {
							tmp35 := aotExternalFn9("Failed to create pipes")
							tmp36 := lang.NewMap(kw_exit, int64(1), kw_out, "", kw_err, tmp35)
							tmp33 = tmp36
						} else {
							var tmp37 any
							{ // let
								// let binding "start-err"
								tmp38, ok := lang.FieldOrMethod(v18, "Start")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v18, "Start")))
								}
								var tmp39 any
								switch reflect.TypeOf(tmp38).Kind() {
								case reflect.Func:
									tmp39 = lang.Apply(tmp38, nil)
								default:
									tmp39 = tmp38
								}
								var v40 any = tmp39
								_ = v40
								var tmp41 any
								tmp42 := lang.Identical(v40, nil)
								tmp43 := aotExternalFn8(tmp42)
								if lang.IsTruthy(tmp43) {
									tmp44 := aotExternalFn10("Failed to start: ", v40)
									tmp45 := lang.NewMap(kw_exit, int64(1), kw_out, "", kw_err, tmp44)
									tmp41 = tmp45
								} else {
									var tmp46 any
									{ // let
										// let binding "vec__10"
										tmp47 := lang.Apply1(io5.ReadAll, v23)
										var v48 any = tmp47
										_ = v48
										// let binding "stdout-bytes"
										tmp49 := runtime.RT.NthDefault(v48, lang.IntCast(int64(0)), nil)
										var v50 any = tmp49
										_ = v50
										// let binding "stdout-read-err"
										tmp51 := runtime.RT.NthDefault(v48, lang.IntCast(int64(1)), nil)
										var v52 any = tmp51
										_ = v52
										// let binding "vec__13"
										tmp53 := lang.Apply1(io5.ReadAll, v30)
										var v54 any = tmp53
										_ = v54
										// let binding "stderr-bytes"
										tmp55 := runtime.RT.NthDefault(v54, lang.IntCast(int64(0)), nil)
										var v56 any = tmp55
										_ = v56
										// let binding "stderr-read-err"
										tmp57 := runtime.RT.NthDefault(v54, lang.IntCast(int64(1)), nil)
										var v58 any = tmp57
										_ = v58
										// let binding "wait-err"
										tmp59, ok := lang.FieldOrMethod(v18, "Wait")
										if !ok {
											panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v18, "Wait")))
										}
										var tmp60 any
										switch reflect.TypeOf(tmp59).Kind() {
										case reflect.Func:
											tmp60 = lang.Apply(tmp59, nil)
										default:
											tmp60 = tmp59
										}
										var v61 any = tmp60
										_ = v61
										// let binding "exit-code"
										var tmp62 any
										tmp63 := lang.Identical(v61, nil)
										if lang.IsTruthy(tmp63) {
											tmp62 = int64(0)
										} else {
											tmp64, ok := lang.FieldOrMethod(v18, "ProcessState")
											if !ok {
												panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v18, "ProcessState")))
											}
											var tmp65 any
											switch reflect.TypeOf(tmp64).Kind() {
											case reflect.Func:
												tmp65 = lang.Apply(tmp64, nil)
											default:
												tmp65 = tmp64
											}
											tmp66, ok := lang.FieldOrMethod(tmp65, "ExitCode")
											if !ok {
												panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp65, "ExitCode")))
											}
											var tmp67 any
											switch reflect.TypeOf(tmp66).Kind() {
											case reflect.Func:
												tmp67 = lang.Apply(tmp66, nil)
											default:
												tmp67 = tmp66
											}
											tmp62 = tmp67
										}
										var v68 any = tmp62
										_ = v68
										var tmp69 any
										tmp70 := lang.Identical(v52, nil)
										if lang.IsTruthy(tmp70) {
											tmp71 := aotDirectFn0(v50)
											tmp69 = tmp71
										} else {
											tmp69 = ""
										}
										var tmp72 any
										tmp73 := lang.Identical(v58, nil)
										if lang.IsTruthy(tmp73) {
											tmp74 := aotDirectFn0(v56)
											tmp72 = tmp74
										} else {
											tmp72 = ""
										}
										tmp75 := lang.NewMap(kw_exit, v68, kw_out, tmp69, kw_err, tmp72)
										tmp46 = tmp75
									} // end let
									tmp41 = tmp46
								}
								tmp37 = tmp41
							} // end let
							tmp33 = tmp37
						}
						tmp6 = tmp33
					} // end let
					tmp3 = tmp6
				}
				return tmp3
			}),
			0,
		)
		aotDirectFn2 = tmp1
		var_ys_DOT_ipc_sh = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_ipc_sh.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(22), kw_column, int(7), kw_end_DASH_line, int(22), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
	// shell
	{
		tmp0 := sym_shell
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				_ = "Execute command via /bin/sh -c (joins args into single command string)"
				var tmp3 any
				{ // let
					// let binding "cmd-str"
					tmp4 := aotExternalFn11(" ", v2)
					var v5 any = tmp4
					_ = v5
					tmp6 := aotDirectFn2.Invoke3("/bin/sh", "-c", v5)
					tmp3 = tmp6
				} // end let
				return tmp3
			}),
			0,
		)
		aotDirectFn3 = tmp1
		var_ys_DOT_ipc_shell = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_ipc_shell.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(49), kw_column, int(7), kw_end_DASH_line, int(49), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
	// process
	{
		tmp0 := sym_process
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				_ = "Execute command via /bin/sh -c (joins args into single command string)"
				tmp3 := checkDerefVar(var_ys_DOT_ipc_shell)
				tmp4 := aotExternalFn0(tmp3, v2)
				return tmp4
			}),
			0,
		)
		aotDirectFn1 = tmp1
		var_ys_DOT_ipc_process = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_ipc_process.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/ipc.glj", kw_line, int(54), kw_column, int(7), kw_end_DASH_line, int(54), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_ipc))
		})
	}
}
