// Code generated by glojure codegen. DO NOT EDIT.

package json

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc1
var aotDirectFn3 lang.FnFunc1
var aotDirectFn4 lang.FnFunc2
var aotDirectFn5 lang.FnFunc2
var aotDirectFn6 lang.FnFunc2
var aotDirectFn7 lang.FnFunc2
var aotDirectFn8 lang.FnFunc2
var aotDirectFn9 lang.FnFunc2

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func aotLinkFn4(vr *lang.Var) lang.FnFunc4 {
	if vr.IsBound() {
		return aotLinkBoundFn4(vr)
	}
	var once sync.Once
	var linked lang.FnFunc4
	return func(p0 any, p1 any, p2 any, p3 any) any {
		if !vr.IsBound() {
			return lang.Apply4(checkDerefVar(vr), p0, p1, p2, p3)
		}
		once.Do(func() { linked = aotLinkBoundFn4(vr) })
		return linked(p0, p1, p2, p3)
	}
}

func aotLinkBoundFn4(vr *lang.Var) lang.FnFunc4 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc4); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn4); ok {
		return fixed.Invoke4
	}
	return func(p0 any, p1 any, p2 any, p3 any) any { return lang.Apply4(fn, p0, p1, p2, p3) }
}

func init() {
	runtime.RegisterNSLoader("ys/json", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "ys.json"
func LoadNS() {
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_c := lang.NewSymbolUnchecked("c")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_dump := lang.NewSymbolUnchecked("dump")
	sym_escape_DASH_string := lang.NewSymbolUnchecked("escape-string")
	sym_false_QMARK_ := lang.NewSymbolUnchecked("false?")
	sym_is_DASH_digit_QMARK_ := lang.NewSymbolUnchecked("is-digit?")
	sym_join := lang.NewSymbolUnchecked("join")
	sym_keyword_QMARK_ := lang.NewSymbolUnchecked("keyword?")
	sym_load := lang.NewSymbolUnchecked("load")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_map_QMARK_ := lang.NewSymbolUnchecked("map?")
	sym_not_EQ_ := lang.NewSymbolUnchecked("not=")
	sym_number_QMARK_ := lang.NewSymbolUnchecked("number?")
	sym_parse_DASH_array := lang.NewSymbolUnchecked("parse-array")
	sym_parse_DASH_number := lang.NewSymbolUnchecked("parse-number")
	sym_parse_DASH_object := lang.NewSymbolUnchecked("parse-object")
	sym_parse_DASH_string := lang.NewSymbolUnchecked("parse-string")
	sym_parse_DASH_value := lang.NewSymbolUnchecked("parse-value")
	sym_pos := lang.NewSymbolUnchecked("pos")
	sym_read_DASH_string := lang.NewSymbolUnchecked("read-string")
	sym_replace := lang.NewSymbolUnchecked("replace")
	sym_s := lang.NewSymbolUnchecked("s")
	sym_sequential_QMARK_ := lang.NewSymbolUnchecked("sequential?")
	sym_skip_DASH_whitespace := lang.NewSymbolUnchecked("skip-whitespace")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	sym_subs := lang.NewSymbolUnchecked("subs")
	sym_true_QMARK_ := lang.NewSymbolUnchecked("true?")
	sym_type := lang.NewSymbolUnchecked("type")
	sym_x := lang.NewSymbolUnchecked("x")
	sym_ys_DOT_json := lang.NewSymbolUnchecked("ys.json")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/false?
	var_clojure_DOT_core_false_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_false_QMARK_)
	// var clojure.core/keyword?
	var_clojure_DOT_core_keyword_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_keyword_QMARK_)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/map?
	var_clojure_DOT_core_map_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_map_QMARK_)
	// var clojure.core/not=
	var_clojure_DOT_core_not_EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym_not_EQ_)
	// var clojure.core/number?
	var_clojure_DOT_core_number_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_number_QMARK_)
	// var clojure.core/read-string
	var_clojure_DOT_core_read_DASH_string := lang.InternVarName(sym_clojure_DOT_core, sym_read_DASH_string)
	// var clojure.core/sequential?
	var_clojure_DOT_core_sequential_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_sequential_QMARK_)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var clojure.core/subs
	var_clojure_DOT_core_subs := lang.InternVarName(sym_clojure_DOT_core, sym_subs)
	// var clojure.core/true?
	var_clojure_DOT_core_true_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_true_QMARK_)
	// var clojure.core/type
	var_clojure_DOT_core_type := lang.InternVarName(sym_clojure_DOT_core, sym_type)
	// var clojure.string/join
	var_clojure_DOT_string_join := lang.InternVarName(sym_clojure_DOT_string, sym_join)
	// var clojure.string/replace
	var_clojure_DOT_string_replace := lang.InternVarName(sym_clojure_DOT_string, sym_replace)
	// var ys.json/dump
	var_ys_DOT_json_dump := lang.InternVarName(sym_ys_DOT_json, sym_dump)
	// var ys.json/escape-string
	var_ys_DOT_json_escape_DASH_string := lang.InternVarName(sym_ys_DOT_json, sym_escape_DASH_string)
	// var ys.json/is-digit?
	var_ys_DOT_json_is_DASH_digit_QMARK_ := lang.InternVarName(sym_ys_DOT_json, sym_is_DASH_digit_QMARK_)
	// var ys.json/load
	var_ys_DOT_json_load := lang.InternVarName(sym_ys_DOT_json, sym_load)
	// var ys.json/parse-array
	var_ys_DOT_json_parse_DASH_array := lang.InternVarName(sym_ys_DOT_json, sym_parse_DASH_array)
	// var ys.json/parse-number
	var_ys_DOT_json_parse_DASH_number := lang.InternVarName(sym_ys_DOT_json, sym_parse_DASH_number)
	// var ys.json/parse-object
	var_ys_DOT_json_parse_DASH_object := lang.InternVarName(sym_ys_DOT_json, sym_parse_DASH_object)
	// var ys.json/parse-string
	var_ys_DOT_json_parse_DASH_string := lang.InternVarName(sym_ys_DOT_json, sym_parse_DASH_string)
	// var ys.json/parse-value
	var_ys_DOT_json_parse_DASH_value := lang.InternVarName(sym_ys_DOT_json, sym_parse_DASH_value)
	// var ys.json/skip-whitespace
	var_ys_DOT_json_skip_DASH_whitespace := lang.InternVarName(sym_ys_DOT_json, sym_skip_DASH_whitespace)
	aotExternalFn0 := aotLinkFn1(var_clojure_DOT_core_true_QMARK_)
	aotExternalFn1 := aotLinkFn1(var_clojure_DOT_core_false_QMARK_)
	aotExternalFn10 := aotLinkFn1(var_clojure_DOT_core_map_QMARK_)
	aotExternalFn11 := aotLinkFn2(var_clojure_DOT_core_map)
	aotExternalFn13 := aotLinkFn4(var_clojure_DOT_core_str)
	aotExternalFn14 := aotLinkFn2(var_clojure_DOT_string_join)
	aotExternalFn15 := aotLinkFn1(var_clojure_DOT_core_sequential_QMARK_)
	aotExternalFn16 := aotLinkFn1(var_clojure_DOT_core_type)
	aotExternalFn17 := aotLinkFn3(var_clojure_DOT_string_replace)
	aotExternalFn2 := aotLinkFn1(var_clojure_DOT_core_keyword_QMARK_)
	aotExternalFn20 := aotLinkFn2(var_clojure_DOT_core_not_EQ_)
	aotExternalFn22 := aotLinkFn2(var_clojure_DOT_core_str)
	aotExternalFn23 := aotLinkFn1(var_clojure_DOT_core_read_DASH_string)
	aotExternalFn24 := aotLinkFn2(var_clojure_DOT_core_apply)
	aotExternalFn3 := aotLinkFn1(var_clojure_DOT_core_str)
	aotExternalFn4 := aotLinkFn3(var_clojure_DOT_core_str)
	aotExternalFn5 := aotLinkFn2(var_clojure_DOT_core__EQ_)
	aotExternalFn7 := aotLinkFn2(var_clojure_DOT_core_subs)
	aotExternalFn8 := aotLinkFn1(var_clojure_DOT_core_string_QMARK_)
	aotExternalFn9 := aotLinkFn1(var_clojure_DOT_core_number_QMARK_)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_ys_DOT_json)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	// dump
	{
		tmp0 := sym_dump
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Convert Clojure data to JSON string"
			var tmp3 any
			tmp4 := lang.Identical(v2, nil)
			if lang.IsTruthy(tmp4) {
				tmp3 = "null"
			} else {
				var tmp5 any
				tmp6 := aotExternalFn0(v2)
				if lang.IsTruthy(tmp6) {
					tmp5 = "true"
				} else {
					var tmp7 any
					tmp8 := aotExternalFn1(v2)
					if lang.IsTruthy(tmp8) {
						tmp7 = "false"
					} else {
						var tmp9 any
						tmp10 := aotExternalFn2(v2)
						if lang.IsTruthy(tmp10) {
							var tmp11 any
							{ // let
								// let binding "s"
								tmp12 := aotExternalFn3(v2)
								var v13 any = tmp12
								_ = v13
								var tmp14 any
								tmp15 := lang.First(v13)
								tmp16 := aotExternalFn5(tmp15, lang.NewChar(58))
								if lang.IsTruthy(tmp16) {
									tmp17 := aotExternalFn7(v13, int64(1))
									tmp14 = tmp17
								} else {
									tmp14 = v13
								}
								tmp18 := aotExternalFn4("\"", tmp14, "\"")
								tmp11 = tmp18
							} // end let
							tmp9 = tmp11
						} else {
							var tmp12 any
							tmp13 := aotExternalFn8(v2)
							if lang.IsTruthy(tmp13) {
								tmp14 := aotDirectFn1(v2)
								tmp15 := aotExternalFn4("\"", tmp14, "\"")
								tmp12 = tmp15
							} else {
								var tmp16 any
								tmp17 := aotExternalFn9(v2)
								if lang.IsTruthy(tmp17) {
									tmp18 := aotExternalFn3(v2)
									tmp16 = tmp18
								} else {
									var tmp19 any
									tmp20 := aotExternalFn10(v2)
									if lang.IsTruthy(tmp20) {
										var tmp21 any
										{ // let
											// let binding "pairs"
											var tmp22 lang.FnFunc1
											tmp22 = lang.FnFunc1(func(p0 any) any {
												v23 := p0
												_ = v23
												var tmp24 any
												{ // let
													// let binding "vec__2"
													var v25 any = v23
													_ = v25
													// let binding "k"
													tmp26 := runtime.RT.NthDefault(v25, lang.IntCast(int64(0)), nil)
													var v27 any = tmp26
													_ = v27
													// let binding "v"
													tmp28 := runtime.RT.NthDefault(v25, lang.IntCast(int64(1)), nil)
													var v29 any = tmp28
													_ = v29
													var tmp30 any
													{ // let
														// let binding "ks"
														tmp31 := aotExternalFn3(v27)
														var v32 any = tmp31
														_ = v32
														// let binding "key-str"
														var tmp33 any
														tmp34 := lang.First(v32)
														tmp35 := aotExternalFn5(tmp34, lang.NewChar(58))
														if lang.IsTruthy(tmp35) {
															tmp36 := aotExternalFn7(v32, int64(1))
															tmp33 = tmp36
														} else {
															tmp33 = v32
														}
														var v37 any = tmp33
														_ = v37
														tmp38 := aotDirectFn1(v37)
														tmp39 := aotDirectFn0(v29)
														tmp40 := aotExternalFn13("\"", tmp38, "\":", tmp39)
														tmp30 = tmp40
													} // end let
													tmp24 = tmp30
												} // end let
												return tmp24
											})
											tmp23 := aotExternalFn11(tmp22, v2)
											var v24 any = tmp23
											_ = v24
											tmp25 := aotExternalFn14(",", v24)
											tmp26 := aotExternalFn4("{", tmp25, "}")
											tmp21 = tmp26
										} // end let
										tmp19 = tmp21
									} else {
										var tmp22 any
										tmp23 := aotExternalFn15(v2)
										if lang.IsTruthy(tmp23) {
											tmp24 := checkDerefVar(var_ys_DOT_json_dump)
											tmp25 := aotExternalFn11(tmp24, v2)
											tmp26 := aotExternalFn14(",", tmp25)
											tmp27 := aotExternalFn4("[", tmp26, "]")
											tmp22 = tmp27
										} else {
											tmp28 := aotExternalFn16(v2)
											tmp29 := aotExternalFn4("Cannot encode ", tmp28, " to JSON")
											tmp30 := lang.Apply1(lang.NewError, tmp29)
											panic(tmp30)
										}
										tmp19 = tmp22
									}
									tmp16 = tmp19
								}
								tmp12 = tmp16
							}
							tmp9 = tmp12
						}
						tmp7 = tmp9
					}
					tmp5 = tmp7
				}
				tmp3 = tmp5
			}
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_ys_DOT_json_dump = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_dump.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/json.glj", kw_line, int(24), kw_column, int(7), kw_end_DASH_line, int(24), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// escape-string
	{
		tmp0 := sym_escape_DASH_string
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Escape special characters in JSON strings"
			tmp3 := aotExternalFn17(v2, "\\", "\\\\")
			tmp4 := aotExternalFn17(tmp3, "\"", "\\\"")
			tmp5 := aotExternalFn17(tmp4, "\n", "\\n")
			tmp6 := aotExternalFn17(tmp5, "\r", "\\r")
			tmp7 := aotExternalFn17(tmp6, "\t", "\\t")
			return tmp7
		})
		aotDirectFn1 = tmp1
		var_ys_DOT_json_escape_DASH_string = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_escape_DASH_string.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/json.glj", kw_line, int(15), kw_column, int(7), kw_end_DASH_line, int(15), kw_end_DASH_column, int(19), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// is-digit?
	{
		tmp0 := sym_is_DASH_digit_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Check if character is a digit"
			var tmp3 any
			{ // let
				// let binding "and__0__auto__"
				tmp4 := runtime.RT.IntCast(v2)
				tmp5 := runtime.RT.IntCast(lang.NewChar(48))
				tmp6 := lang.Numbers.Gte(tmp4, tmp5)
				var v7 any = tmp6
				_ = v7
				var tmp8 any
				if lang.IsTruthy(v7) {
					tmp9 := runtime.RT.IntCast(v2)
					tmp10 := runtime.RT.IntCast(lang.NewChar(57))
					tmp11 := lang.Numbers.Lte(tmp9, tmp10)
					tmp8 = tmp11
				} else {
					tmp8 = v7
				}
				tmp3 = tmp8
			} // end let
			return tmp3
		})
		aotDirectFn2 = tmp1
		var_ys_DOT_json_is_DASH_digit_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_is_DASH_digit_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/json.glj", kw_line, int(89), kw_column, int(8), kw_end_DASH_line, int(89), kw_end_DASH_column, int(16), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_c)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// load
	{
		tmp0 := sym_load
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			_ = "Parse JSON string to Clojure data"
			var tmp3 any
			{ // let
				// let binding "vec__18"
				tmp4 := aotDirectFn8(v2, int64(0))
				var v5 any = tmp4
				_ = v5
				// let binding "value"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "_"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				tmp3 = v7
			} // end let
			return tmp3
		})
		aotDirectFn3 = tmp1
		var_ys_DOT_json_load = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_load.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "ys/json.glj", kw_line, int(170), kw_column, int(7), kw_end_DASH_line, int(170), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_s)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// parse-array
	{
		tmp0 := sym_parse_DASH_array
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Parse a JSON array starting at pos, return [value new-pos]"
			var tmp4 any
			{ // let
				// let binding "i"
				tmp5 := lang.Numbers.Inc(v3)
				tmp6 := aotDirectFn9(v2, tmp5)
				var v7 any = tmp6
				_ = v7
				// let binding "values"
				tmp8 := lang.NewVector()
				var v9 any = tmp8
				_ = v9
				for {
					var tmp10 any
					tmp11 := lang.Count(v2)
					tmp12 := lang.Numbers.Gte(v7, tmp11)
					if lang.IsTruthy(tmp12) {
						tmp13 := lang.Apply1(lang.NewError, "Unterminated array")
						panic(tmp13)
					} else {
						var tmp14 any
						{ // let
							// let binding "c"
							tmp15 := runtime.RT.Nth(v2, lang.IntCast(v7))
							var v16 any = tmp15
							_ = v16
							var tmp17 any
							tmp18 := aotExternalFn5(v16, lang.NewChar(93))
							if lang.IsTruthy(tmp18) {
								tmp19 := lang.Numbers.Inc(v7)
								tmp20 := lang.NewVector(v9, tmp19)
								tmp17 = tmp20
							} else {
								var tmp21 any
								var tmp22 any
								{ // let
									// let binding "and__0__auto__"
									tmp23 := lang.IsEmpty(v9)
									var v24 any = tmp23
									_ = v24
									var tmp25 any
									if lang.IsTruthy(v24) {
										tmp26 := aotExternalFn20(v16, lang.NewChar(44))
										tmp25 = tmp26
									} else {
										tmp25 = v24
									}
									tmp22 = tmp25
								} // end let
								if lang.IsTruthy(tmp22) {
									var tmp23 any
									{ // let
										// let binding "vec__6"
										tmp24 := aotDirectFn8(v2, v7)
										var v25 any = tmp24
										_ = v25
										// let binding "v"
										tmp26 := runtime.RT.NthDefault(v25, lang.IntCast(int64(0)), nil)
										var v27 any = tmp26
										_ = v27
										// let binding "new-pos"
										tmp28 := runtime.RT.NthDefault(v25, lang.IntCast(int64(1)), nil)
										var v29 any = tmp28
										_ = v29
										// let binding "new-pos"
										tmp30 := aotDirectFn9(v2, v29)
										var v31 any = tmp30
										_ = v31
										var tmp32 any = v31
										tmp34 := lang.ConjAny(v9, v27)
										var tmp33 any = tmp34
										v7 = tmp32
										v9 = tmp33
										continue
									} // end let
									tmp21 = tmp23
								} else {
									var tmp24 any
									tmp25 := aotExternalFn5(v16, lang.NewChar(44))
									if lang.IsTruthy(tmp25) {
										var tmp26 any
										{ // let
											// let binding "new-pos"
											tmp27 := lang.Numbers.Inc(v7)
											tmp28 := aotDirectFn9(v2, tmp27)
											var v29 any = tmp28
											_ = v29
											// let binding "vec__9"
											tmp30 := aotDirectFn8(v2, v29)
											var v31 any = tmp30
											_ = v31
											// let binding "v"
											tmp32 := runtime.RT.NthDefault(v31, lang.IntCast(int64(0)), nil)
											var v33 any = tmp32
											_ = v33
											// let binding "new-pos"
											tmp34 := runtime.RT.NthDefault(v31, lang.IntCast(int64(1)), nil)
											var v35 any = tmp34
											_ = v35
											// let binding "new-pos"
											tmp36 := aotDirectFn9(v2, v35)
											var v37 any = tmp36
											_ = v37
											var tmp38 any = v37
											tmp40 := lang.ConjAny(v9, v33)
											var tmp39 any = tmp40
											v7 = tmp38
											v9 = tmp39
											continue
										} // end let
										tmp24 = tmp26
									} else {
										tmp27 := aotExternalFn22("Unexpected character in array: ", v16)
										tmp28 := lang.Apply1(lang.NewError, tmp27)
										panic(tmp28)
									}
									tmp21 = tmp24
								}
								tmp17 = tmp21
							}
							tmp14 = tmp17
						} // end let
						tmp10 = tmp14
					}
					tmp4 = tmp10
					break
				}
			} // end let
			return tmp4
		})
		aotDirectFn4 = tmp1
		var_ys_DOT_json_parse_DASH_array = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_parse_DASH_array.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/json.glj", kw_line, int(107), kw_column, int(8), kw_end_DASH_line, int(107), kw_end_DASH_column, int(18), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_pos)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// parse-object
	{
		tmp0 := sym_parse_DASH_object
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Parse a JSON object starting at pos, return [value new-pos]"
			var tmp4 any
			{ // let
				// let binding "i"
				tmp5 := lang.Numbers.Inc(v3)
				tmp6 := aotDirectFn9(v2, tmp5)
				var v7 any = tmp6
				_ = v7
				// let binding "obj"
				tmp8 := lang.NewMap()
				var v9 any = tmp8
				_ = v9
				for {
					var tmp10 any
					tmp11 := lang.Count(v2)
					tmp12 := lang.Numbers.Gte(v7, tmp11)
					if lang.IsTruthy(tmp12) {
						tmp13 := lang.Apply1(lang.NewError, "Unterminated object")
						panic(tmp13)
					} else {
						var tmp14 any
						{ // let
							// let binding "c"
							tmp15 := runtime.RT.Nth(v2, lang.IntCast(v7))
							var v16 any = tmp15
							_ = v16
							var tmp17 any
							tmp18 := aotExternalFn5(v16, lang.NewChar(125))
							if lang.IsTruthy(tmp18) {
								tmp19 := lang.Numbers.Inc(v7)
								tmp20 := lang.NewVector(v9, tmp19)
								tmp17 = tmp20
							} else {
								var tmp21 any
								tmp22 := aotExternalFn5(v16, lang.NewChar(34))
								if lang.IsTruthy(tmp22) {
									var tmp23 any
									{ // let
										// let binding "vec__12"
										tmp24 := aotDirectFn7(v2, v7)
										var v25 any = tmp24
										_ = v25
										// let binding "k"
										tmp26 := runtime.RT.NthDefault(v25, lang.IntCast(int64(0)), nil)
										var v27 any = tmp26
										_ = v27
										// let binding "new-pos"
										tmp28 := runtime.RT.NthDefault(v25, lang.IntCast(int64(1)), nil)
										var v29 any = tmp28
										_ = v29
										// let binding "new-pos"
										tmp30 := aotDirectFn9(v2, v29)
										var v31 any = tmp30
										_ = v31
										var tmp32 any
										tmp33 := runtime.RT.Nth(v2, lang.IntCast(v31))
										tmp34 := aotExternalFn20(tmp33, lang.NewChar(58))
										if lang.IsTruthy(tmp34) {
											tmp35 := lang.Apply1(lang.NewError, "Expected : after object key")
											panic(tmp35)
										} else {
											var tmp36 any
											{ // let
												// let binding "new-pos"
												tmp37 := lang.Numbers.Inc(v31)
												tmp38 := aotDirectFn9(v2, tmp37)
												var v39 any = tmp38
												_ = v39
												// let binding "vec__15"
												tmp40 := aotDirectFn8(v2, v39)
												var v41 any = tmp40
												_ = v41
												// let binding "v"
												tmp42 := runtime.RT.NthDefault(v41, lang.IntCast(int64(0)), nil)
												var v43 any = tmp42
												_ = v43
												// let binding "new-pos"
												tmp44 := runtime.RT.NthDefault(v41, lang.IntCast(int64(1)), nil)
												var v45 any = tmp44
												_ = v45
												// let binding "new-pos"
												tmp46 := aotDirectFn9(v2, v45)
												var v47 any = tmp46
												_ = v47
												// let binding "next-c"
												var tmp48 any
												tmp49 := lang.Count(v2)
												tmp50 := lang.Numbers.Gte(v47, tmp49)
												if lang.IsTruthy(tmp50) {
												} else {
													tmp51 := runtime.RT.Nth(v2, lang.IntCast(v47))
													tmp48 = tmp51
												}
												var v52 any = tmp48
												_ = v52
												var tmp53 any
												tmp54 := aotExternalFn5(v52, lang.NewChar(44))
												if lang.IsTruthy(tmp54) {
													tmp56 := lang.Numbers.Inc(v47)
													tmp57 := aotDirectFn9(v2, tmp56)
													var tmp55 any = tmp57
													var tmp59 any = v9
													tmp59 = lang.Assoc(tmp59, v27, v43)
													var tmp58 any = tmp59
													v7 = tmp55
													v9 = tmp58
													continue
												} else {
													var tmp60 any = v47
													var tmp62 any = v9
													tmp62 = lang.Assoc(tmp62, v27, v43)
													var tmp61 any = tmp62
													v7 = tmp60
													v9 = tmp61
													continue
												}
												tmp36 = tmp53
											} // end let
											tmp32 = tmp36
										}
										tmp23 = tmp32
									} // end let
									tmp21 = tmp23
								} else {
									tmp24 := aotExternalFn22("Unexpected character in object: ", v16)
									tmp25 := lang.Apply1(lang.NewError, tmp24)
									panic(tmp25)
								}
								tmp17 = tmp21
							}
							tmp14 = tmp17
						} // end let
						tmp10 = tmp14
					}
					tmp4 = tmp10
					break
				}
			} // end let
			return tmp4
		})
		aotDirectFn6 = tmp1
		var_ys_DOT_json_parse_DASH_object = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_parse_DASH_object.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/json.glj", kw_line, int(125), kw_column, int(8), kw_end_DASH_line, int(125), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_pos)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// parse-value
	{
		tmp0 := sym_parse_DASH_value
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Parse a JSON value starting at pos, return [value new-pos]"
			var tmp4 any
			{ // let
				// let binding "pos"
				tmp5 := aotDirectFn9(v2, v3)
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				tmp8 := lang.Count(v2)
				tmp9 := lang.Numbers.Gte(v6, tmp8)
				if lang.IsTruthy(tmp9) {
					tmp10 := lang.Apply1(lang.NewError, "Unexpected end of input")
					panic(tmp10)
				} else {
					var tmp11 any
					{ // let
						// let binding "c"
						tmp12 := runtime.RT.Nth(v2, lang.IntCast(v6))
						var v13 any = tmp12
						_ = v13
						var tmp14 any
						tmp15 := aotExternalFn5(v13, lang.NewChar(34))
						if lang.IsTruthy(tmp15) {
							tmp16 := aotDirectFn7(v2, v6)
							tmp14 = tmp16
						} else {
							var tmp17 any
							tmp18 := aotExternalFn5(v13, lang.NewChar(123))
							if lang.IsTruthy(tmp18) {
								tmp19 := aotDirectFn6(v2, v6)
								tmp17 = tmp19
							} else {
								var tmp20 any
								tmp21 := aotExternalFn5(v13, lang.NewChar(91))
								if lang.IsTruthy(tmp21) {
									tmp22 := aotDirectFn4(v2, v6)
									tmp20 = tmp22
								} else {
									var tmp23 any
									var tmp24 any
									{ // let
										// let binding "or__0__auto__"
										tmp25 := aotDirectFn2(v13)
										var v26 any = tmp25
										_ = v26
										var tmp27 any
										if lang.IsTruthy(v26) {
											tmp27 = v26
										} else {
											tmp28 := aotExternalFn5(v13, lang.NewChar(45))
											tmp27 = tmp28
										}
										tmp24 = tmp27
									} // end let
									if lang.IsTruthy(tmp24) {
										tmp25 := aotDirectFn5(v2, v6)
										tmp23 = tmp25
									} else {
										var tmp26 any
										var tmp27 any
										{ // let
											// let binding "and__0__auto__"
											tmp28 := aotExternalFn5(v13, lang.NewChar(116))
											var v29 any = tmp28
											_ = v29
											var tmp30 any
											if lang.IsTruthy(v29) {
												var tmp31 any
												{ // let
													// let binding "and__0__auto__"
													tmp32 := lang.Numbers.Add(v6, int64(4))
													tmp33 := lang.Count(v2)
													tmp34 := lang.Numbers.Lte(tmp32, tmp33)
													var v35 any = tmp34
													_ = v35
													var tmp36 any
													if lang.IsTruthy(v35) {
														var tmp37 any
														{ // let
															// let binding "and__0__auto__"
															tmp38 := lang.Numbers.Inc(v6)
															tmp39 := runtime.RT.Nth(v2, lang.IntCast(tmp38))
															tmp40 := aotExternalFn5(tmp39, lang.NewChar(114))
															var v41 any = tmp40
															_ = v41
															var tmp42 any
															if lang.IsTruthy(v41) {
																var tmp43 any
																{ // let
																	// let binding "and__0__auto__"
																	tmp44 := lang.Numbers.Add(v6, int64(2))
																	tmp45 := runtime.RT.Nth(v2, lang.IntCast(tmp44))
																	tmp46 := aotExternalFn5(tmp45, lang.NewChar(117))
																	var v47 any = tmp46
																	_ = v47
																	var tmp48 any
																	if lang.IsTruthy(v47) {
																		tmp49 := lang.Numbers.Add(v6, int64(3))
																		tmp50 := runtime.RT.Nth(v2, lang.IntCast(tmp49))
																		tmp51 := aotExternalFn5(tmp50, lang.NewChar(101))
																		tmp48 = tmp51
																	} else {
																		tmp48 = v47
																	}
																	tmp43 = tmp48
																} // end let
																tmp42 = tmp43
															} else {
																tmp42 = v41
															}
															tmp37 = tmp42
														} // end let
														tmp36 = tmp37
													} else {
														tmp36 = v35
													}
													tmp31 = tmp36
												} // end let
												tmp30 = tmp31
											} else {
												tmp30 = v29
											}
											tmp27 = tmp30
										} // end let
										if lang.IsTruthy(tmp27) {
											tmp28 := lang.Numbers.Add(v6, int64(4))
											tmp29 := lang.NewVector(true, tmp28)
											tmp26 = tmp29
										} else {
											var tmp30 any
											var tmp31 any
											{ // let
												// let binding "and__0__auto__"
												tmp32 := aotExternalFn5(v13, lang.NewChar(102))
												var v33 any = tmp32
												_ = v33
												var tmp34 any
												if lang.IsTruthy(v33) {
													var tmp35 any
													{ // let
														// let binding "and__0__auto__"
														tmp36 := lang.Numbers.Add(v6, int64(5))
														tmp37 := lang.Count(v2)
														tmp38 := lang.Numbers.Lte(tmp36, tmp37)
														var v39 any = tmp38
														_ = v39
														var tmp40 any
														if lang.IsTruthy(v39) {
															var tmp41 any
															{ // let
																// let binding "and__0__auto__"
																tmp42 := lang.Numbers.Inc(v6)
																tmp43 := runtime.RT.Nth(v2, lang.IntCast(tmp42))
																tmp44 := aotExternalFn5(tmp43, lang.NewChar(97))
																var v45 any = tmp44
																_ = v45
																var tmp46 any
																if lang.IsTruthy(v45) {
																	var tmp47 any
																	{ // let
																		// let binding "and__0__auto__"
																		tmp48 := lang.Numbers.Add(v6, int64(2))
																		tmp49 := runtime.RT.Nth(v2, lang.IntCast(tmp48))
																		tmp50 := aotExternalFn5(tmp49, lang.NewChar(108))
																		var v51 any = tmp50
																		_ = v51
																		var tmp52 any
																		if lang.IsTruthy(v51) {
																			var tmp53 any
																			{ // let
																				// let binding "and__0__auto__"
																				tmp54 := lang.Numbers.Add(v6, int64(3))
																				tmp55 := runtime.RT.Nth(v2, lang.IntCast(tmp54))
																				tmp56 := aotExternalFn5(tmp55, lang.NewChar(115))
																				var v57 any = tmp56
																				_ = v57
																				var tmp58 any
																				if lang.IsTruthy(v57) {
																					tmp59 := lang.Numbers.Add(v6, int64(4))
																					tmp60 := runtime.RT.Nth(v2, lang.IntCast(tmp59))
																					tmp61 := aotExternalFn5(tmp60, lang.NewChar(101))
																					tmp58 = tmp61
																				} else {
																					tmp58 = v57
																				}
																				tmp53 = tmp58
																			} // end let
																			tmp52 = tmp53
																		} else {
																			tmp52 = v51
																		}
																		tmp47 = tmp52
																	} // end let
																	tmp46 = tmp47
																} else {
																	tmp46 = v45
																}
																tmp41 = tmp46
															} // end let
															tmp40 = tmp41
														} else {
															tmp40 = v39
														}
														tmp35 = tmp40
													} // end let
													tmp34 = tmp35
												} else {
													tmp34 = v33
												}
												tmp31 = tmp34
											} // end let
											if lang.IsTruthy(tmp31) {
												tmp32 := lang.Numbers.Add(v6, int64(5))
												tmp33 := lang.NewVector(false, tmp32)
												tmp30 = tmp33
											} else {
												var tmp34 any
												var tmp35 any
												{ // let
													// let binding "and__0__auto__"
													tmp36 := aotExternalFn5(v13, lang.NewChar(110))
													var v37 any = tmp36
													_ = v37
													var tmp38 any
													if lang.IsTruthy(v37) {
														var tmp39 any
														{ // let
															// let binding "and__0__auto__"
															tmp40 := lang.Numbers.Add(v6, int64(4))
															tmp41 := lang.Count(v2)
															tmp42 := lang.Numbers.Lte(tmp40, tmp41)
															var v43 any = tmp42
															_ = v43
															var tmp44 any
															if lang.IsTruthy(v43) {
																var tmp45 any
																{ // let
																	// let binding "and__0__auto__"
																	tmp46 := lang.Numbers.Inc(v6)
																	tmp47 := runtime.RT.Nth(v2, lang.IntCast(tmp46))
																	tmp48 := aotExternalFn5(tmp47, lang.NewChar(117))
																	var v49 any = tmp48
																	_ = v49
																	var tmp50 any
																	if lang.IsTruthy(v49) {
																		var tmp51 any
																		{ // let
																			// let binding "and__0__auto__"
																			tmp52 := lang.Numbers.Add(v6, int64(2))
																			tmp53 := runtime.RT.Nth(v2, lang.IntCast(tmp52))
																			tmp54 := aotExternalFn5(tmp53, lang.NewChar(108))
																			var v55 any = tmp54
																			_ = v55
																			var tmp56 any
																			if lang.IsTruthy(v55) {
																				tmp57 := lang.Numbers.Add(v6, int64(3))
																				tmp58 := runtime.RT.Nth(v2, lang.IntCast(tmp57))
																				tmp59 := aotExternalFn5(tmp58, lang.NewChar(108))
																				tmp56 = tmp59
																			} else {
																				tmp56 = v55
																			}
																			tmp51 = tmp56
																		} // end let
																		tmp50 = tmp51
																	} else {
																		tmp50 = v49
																	}
																	tmp45 = tmp50
																} // end let
																tmp44 = tmp45
															} else {
																tmp44 = v43
															}
															tmp39 = tmp44
														} // end let
														tmp38 = tmp39
													} else {
														tmp38 = v37
													}
													tmp35 = tmp38
												} // end let
												if lang.IsTruthy(tmp35) {
													tmp36 := lang.Numbers.Add(v6, int64(4))
													tmp37 := lang.NewVector(nil, tmp36)
													tmp34 = tmp37
												} else {
													tmp38 := aotExternalFn22("Unexpected character: ", v13)
													tmp39 := lang.Apply1(lang.NewError, tmp38)
													panic(tmp39)
												}
												tmp30 = tmp34
											}
											tmp26 = tmp30
										}
										tmp23 = tmp26
									}
									tmp20 = tmp23
								}
								tmp17 = tmp20
							}
							tmp14 = tmp17
						}
						tmp11 = tmp14
					} // end let
					tmp7 = tmp11
				}
				tmp4 = tmp7
			} // end let
			return tmp4
		})
		aotDirectFn8 = tmp1
		var_ys_DOT_json_parse_DASH_value = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_parse_DASH_value.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/json.glj", kw_line, int(147), kw_column, int(8), kw_end_DASH_line, int(147), kw_end_DASH_column, int(18), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_pos)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// skip-whitespace
	{
		tmp0 := sym_skip_DASH_whitespace
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Skip whitespace characters, return new position"
			var tmp4 any
			{ // let
				// let binding "i"
				var v5 any = v3
				_ = v5
				for {
					var tmp6 any
					tmp7 := lang.Count(v2)
					tmp8 := lang.Numbers.Gte(v5, tmp7)
					if lang.IsTruthy(tmp8) {
						tmp6 = v5
					} else {
						var tmp9 any
						{ // let
							// let binding "c"
							tmp10 := runtime.RT.Nth(v2, lang.IntCast(v5))
							var v11 any = tmp10
							_ = v11
							// let binding "cc"
							tmp12 := runtime.RT.IntCast(v11)
							var v13 any = tmp12
							_ = v13
							var tmp14 any
							var tmp15 any
							{ // let
								// let binding "or__0__auto__"
								tmp16 := aotExternalFn5(v13, int64(32))
								var v17 any = tmp16
								_ = v17
								var tmp18 any
								if lang.IsTruthy(v17) {
									tmp18 = v17
								} else {
									var tmp19 any
									{ // let
										// let binding "or__0__auto__"
										tmp20 := aotExternalFn5(v13, int64(10))
										var v21 any = tmp20
										_ = v21
										var tmp22 any
										if lang.IsTruthy(v21) {
											tmp22 = v21
										} else {
											var tmp23 any
											{ // let
												// let binding "or__0__auto__"
												tmp24 := aotExternalFn5(v13, int64(13))
												var v25 any = tmp24
												_ = v25
												var tmp26 any
												if lang.IsTruthy(v25) {
													tmp26 = v25
												} else {
													tmp27 := aotExternalFn5(v13, int64(9))
													tmp26 = tmp27
												}
												tmp23 = tmp26
											} // end let
											tmp22 = tmp23
										}
										tmp19 = tmp22
									} // end let
									tmp18 = tmp19
								}
								tmp15 = tmp18
							} // end let
							if lang.IsTruthy(tmp15) {
								tmp17 := lang.Numbers.Inc(v5)
								var tmp16 any = tmp17
								v5 = tmp16
								continue
							} else {
								tmp14 = v5
							}
							tmp9 = tmp14
						} // end let
						tmp6 = tmp9
					}
					tmp4 = tmp6
					break
				}
			} // end let
			return tmp4
		})
		aotDirectFn9 = tmp1
		var_ys_DOT_json_skip_DASH_whitespace = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_skip_DASH_whitespace.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/json.glj", kw_line, int(54), kw_column, int(8), kw_end_DASH_line, int(54), kw_end_DASH_column, int(22), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_pos)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// parse-number
	{
		tmp0 := sym_parse_DASH_number
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Parse a JSON number starting at pos, return [value new-pos]"
			var tmp4 any
			{ // let
				// let binding "i"
				var v5 any = v3
				_ = v5
				// let binding "chars"
				tmp6 := lang.NewVector()
				var v7 any = tmp6
				_ = v7
				for {
					var tmp8 any
					tmp9 := lang.Count(v2)
					tmp10 := lang.Numbers.Gte(v5, tmp9)
					if lang.IsTruthy(tmp10) {
						tmp11 := checkDerefVar(var_clojure_DOT_core_str)
						tmp12 := aotExternalFn24(tmp11, v7)
						tmp13 := aotExternalFn23(tmp12)
						tmp14 := lang.NewVector(tmp13, v5)
						tmp8 = tmp14
					} else {
						var tmp15 any
						{ // let
							// let binding "c"
							tmp16 := runtime.RT.Nth(v2, lang.IntCast(v5))
							var v17 any = tmp16
							_ = v17
							var tmp18 any
							var tmp19 any
							{ // let
								// let binding "or__0__auto__"
								tmp20 := aotDirectFn2(v17)
								var v21 any = tmp20
								_ = v21
								var tmp22 any
								if lang.IsTruthy(v21) {
									tmp22 = v21
								} else {
									var tmp23 any
									{ // let
										// let binding "or__0__auto__"
										tmp24 := aotExternalFn5(v17, lang.NewChar(46))
										var v25 any = tmp24
										_ = v25
										var tmp26 any
										if lang.IsTruthy(v25) {
											tmp26 = v25
										} else {
											var tmp27 any
											{ // let
												// let binding "or__0__auto__"
												tmp28 := aotExternalFn5(v17, lang.NewChar(45))
												var v29 any = tmp28
												_ = v29
												var tmp30 any
												if lang.IsTruthy(v29) {
													tmp30 = v29
												} else {
													var tmp31 any
													{ // let
														// let binding "or__0__auto__"
														tmp32 := aotExternalFn5(v17, lang.NewChar(43))
														var v33 any = tmp32
														_ = v33
														var tmp34 any
														if lang.IsTruthy(v33) {
															tmp34 = v33
														} else {
															var tmp35 any
															{ // let
																// let binding "or__0__auto__"
																tmp36 := aotExternalFn5(v17, lang.NewChar(101))
																var v37 any = tmp36
																_ = v37
																var tmp38 any
																if lang.IsTruthy(v37) {
																	tmp38 = v37
																} else {
																	tmp39 := aotExternalFn5(v17, lang.NewChar(69))
																	tmp38 = tmp39
																}
																tmp35 = tmp38
															} // end let
															tmp34 = tmp35
														}
														tmp31 = tmp34
													} // end let
													tmp30 = tmp31
												}
												tmp27 = tmp30
											} // end let
											tmp26 = tmp27
										}
										tmp23 = tmp26
									} // end let
									tmp22 = tmp23
								}
								tmp19 = tmp22
							} // end let
							if lang.IsTruthy(tmp19) {
								tmp21 := lang.Numbers.Inc(v5)
								var tmp20 any = tmp21
								tmp23 := lang.ConjAny(v7, v17)
								var tmp22 any = tmp23
								v5 = tmp20
								v7 = tmp22
								continue
							} else {
								tmp24 := checkDerefVar(var_clojure_DOT_core_str)
								tmp25 := aotExternalFn24(tmp24, v7)
								tmp26 := aotExternalFn23(tmp25)
								tmp27 := lang.NewVector(tmp26, v5)
								tmp18 = tmp27
							}
							tmp15 = tmp18
						} // end let
						tmp8 = tmp15
					}
					tmp4 = tmp8
					break
				}
			} // end let
			return tmp4
		})
		aotDirectFn5 = tmp1
		var_ys_DOT_json_parse_DASH_number = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_parse_DASH_number.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/json.glj", kw_line, int(94), kw_column, int(8), kw_end_DASH_line, int(94), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_pos)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
	// parse-string
	{
		tmp0 := sym_parse_DASH_string
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			_ = "Parse a JSON string starting at pos, return [value new-pos]"
			var tmp4 any
			{ // let
				// let binding "i"
				tmp5 := lang.Numbers.Inc(v3)
				var v6 any = tmp5
				_ = v6
				// let binding "chars"
				tmp7 := lang.NewVector()
				var v8 any = tmp7
				_ = v8
				for {
					var tmp9 any
					tmp10 := lang.Count(v2)
					tmp11 := lang.Numbers.Gte(v6, tmp10)
					if lang.IsTruthy(tmp11) {
						tmp12 := lang.Apply1(lang.NewError, "Unterminated string")
						panic(tmp12)
					} else {
						var tmp13 any
						{ // let
							// let binding "c"
							tmp14 := runtime.RT.Nth(v2, lang.IntCast(v6))
							var v15 any = tmp14
							_ = v15
							var tmp16 any
							tmp17 := aotExternalFn5(v15, lang.NewChar(34))
							if lang.IsTruthy(tmp17) {
								tmp18 := checkDerefVar(var_clojure_DOT_core_str)
								tmp19 := aotExternalFn24(tmp18, v8)
								tmp20 := lang.Numbers.Inc(v6)
								tmp21 := lang.NewVector(tmp19, tmp20)
								tmp16 = tmp21
							} else {
								var tmp22 any
								tmp23 := aotExternalFn5(v15, lang.NewChar(92))
								if lang.IsTruthy(tmp23) {
									var tmp24 any
									tmp25 := lang.Numbers.Inc(v6)
									tmp26 := lang.Count(v2)
									tmp27 := lang.Numbers.Gte(tmp25, tmp26)
									if lang.IsTruthy(tmp27) {
										tmp28 := lang.Apply1(lang.NewError, "Unterminated escape sequence")
										panic(tmp28)
									} else {
										var tmp29 any
										{ // let
											// let binding "next-c"
											tmp30 := lang.Numbers.Inc(v6)
											tmp31 := runtime.RT.Nth(v2, lang.IntCast(tmp30))
											var v32 any = tmp31
											_ = v32
											tmp34 := lang.Numbers.Add(v6, int64(2))
											var tmp33 any = tmp34
											var tmp36 any
											{ // let
												// let binding "G__5"
												var v37 any = v32
												_ = v37
												// case
												var tmp38 any
												var tmp39 int64
												tmp39 = int64(lang.Hash(v37))
												// case entry 0 (key=34, collision=false)
												if tmp39 == 34 {
													if lang.Equals(v37, lang.NewChar(34)) {
														tmp38 = lang.NewChar(34)
													} else {
														tmp38 = v32
													}
													// case entry 1 (key=47, collision=false)
												} else if tmp39 == 47 {
													if lang.Equals(v37, lang.NewChar(47)) {
														tmp38 = lang.NewChar(47)
													} else {
														tmp38 = v32
													}
													// case entry 2 (key=92, collision=false)
												} else if tmp39 == 92 {
													if lang.Equals(v37, lang.NewChar(92)) {
														tmp38 = lang.NewChar(92)
													} else {
														tmp38 = v32
													}
													// case entry 3 (key=110, collision=false)
												} else if tmp39 == 110 {
													if lang.Equals(v37, lang.NewChar(110)) {
														tmp38 = lang.NewChar(10)
													} else {
														tmp38 = v32
													}
													// case entry 4 (key=114, collision=false)
												} else if tmp39 == 114 {
													if lang.Equals(v37, lang.NewChar(114)) {
														tmp38 = lang.NewChar(13)
													} else {
														tmp38 = v32
													}
													// case entry 5 (key=116, collision=false)
												} else if tmp39 == 116 {
													if lang.Equals(v37, lang.NewChar(116)) {
														tmp38 = lang.NewChar(9)
													} else {
														tmp38 = v32
													}
												} else {
													tmp38 = v32
												}
												tmp36 = tmp38
											} // end let
											tmp37 := lang.ConjAny(v8, tmp36)
											var tmp35 any = tmp37
											v6 = tmp33
											v8 = tmp35
											continue
										} // end let
										tmp24 = tmp29
									}
									tmp22 = tmp24
								} else {
									tmp31 := lang.Numbers.Inc(v6)
									var tmp30 any = tmp31
									tmp33 := lang.ConjAny(v8, v15)
									var tmp32 any = tmp33
									v6 = tmp30
									v8 = tmp32
									continue
								}
								tmp16 = tmp22
							}
							tmp13 = tmp16
						} // end let
						tmp9 = tmp13
					}
					tmp4 = tmp9
					break
				}
			} // end let
			return tmp4
		})
		aotDirectFn7 = tmp1
		var_ys_DOT_json_parse_DASH_string = ns.InternWithValue(tmp0, tmp1, true)
		var_ys_DOT_json_parse_DASH_string.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "ys/json.glj", kw_line, int(65), kw_column, int(8), kw_end_DASH_line, int(65), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_pos)), kw_ns, lang.FindOrCreateNamespace(sym_ys_DOT_json))
		})
	}
}
